### ISSUE TITLE
Pinned tabs

### ISSUE THREAD

**Issue by RichardDavies** [Morikko/sync-tab-groups#1]
It doesn't seem to work with as I would expect with pinned tabs. They are treated as part of the current group and are all closed/reopened when switching between groups. I would prefer pinned tabs to be independent of the tab groups. Switching between groups shouldn't change or reload any of the pinned tabs.

**Comment by Morikko** [comment]
You expect the behavior like the previous tab groups extension. 
I didn't implement it now as it is a bit trickier to manage with many windows.
However, I agree with you, this behavior is interesting. I will see how to add this feature soon.

**Comment by skimpax** [comment]
+1
Another use case to illustrate the need of this enhancement:
Open a live music streaming session to your favorite provider, pin this tab, switch group => music session get closed. You won't be able to resume this music session.

**Comment by Morikko** [comment]
Resolve in 0.1.4 ( !! need to change the setting !! )

**Comment by maddhin** [comment]
I ticked the box in the settings but if I add a pinned tab, it still gets closed with the group and is not added to the other groups. (using v0.3)

**Comment by Morikko** [comment]
Box ticked: pinned tabs are closed and kept in the closed group
Box Not ticked: pinned tabs stay in the window and only unpinned tabs are closed/opened

You are looking for the second case isn't it ?

**Comment by maddhin** [comment]
hm... Yes, but if I remember correctly (just switched back to FF56), I had the box ticked and as the description said what you write about the unticked box... Maybe just a translation error? I'm using the German version.

**Comment by maddhin** [comment]
yeah, translation issue:

the German line should be:

"message": "Angeheftete Tabs zu Gruppen hinzufügen (Wenn inaktiv, werden diese beim Wechsel einer Gruppe nicht geschlossen)",

There was a "nicht" missing...
