### ISSUE TITLE
Permissions explanation.

### ISSUE THREAD

**Issue by PresGas** [Morikko/sync-tab-groups#106]
Hello! Why does the plugin require "Download files and read and modify the browser’s download history"? All the other permissions I get for a plugin of this nature, but don't get this one. It is holding me back from trying it.

Thanks!

**Comment by Morikko** [comment]
Extension Permissions

- Tabs: Access to your tabs proprieties for saving them among the groups
-  Storage: Save your groups on disk for not losing them when quitting
-  Notifications: Giving you feedback
-  Context Menu: Adding elements on right click on tabs and the extension icon
-   Sessions: Find which group is in a window even after restarting Firefox
-   **Downloads: Save your groups in a file for exporting and doing backup**.

It is for saving on the disk.

**Comment by Morikko** [comment]
You can check `browser.downloads` in this repo to see where it is used.
