### ISSUE TITLE
Suggestion/Request

### ISSUE THREAD

**Issue by mikhoul** [Morikko/sync-tab-groups#108]
A good feature would be to ad the option (unless the option exist and I missed it) to "lazy load" all tab except one active tab when we switch from one group to another instead of loading all the tabs from the group each time we move from one group to another. 

**For your reference:** https://developers.google.com/web/updates/2015/09/tab-discarding  and chrome.tabs.discard  (Firefox have the same API too)

Thanks for this extension! :octocat:

**Comment by Morikko** [comment]
It is already in place. See [Discarded tabs wiki page](https://github.com/Morikko/sync-tab-groups/wiki/Discarded-tabs).

Thank you for using sync tab groups !
