### ISSUE TITLE
Always loose ungrouped tabs when open a group

### ISSUE THREAD

**Issue by ArtemKuchin** [Morikko/sync-tab-groups#111]
Maybe i am doing something wrong, but i cannot figure out how to do it correctly.
I lost my tabs because of this some many times and have not found a solution
that it is now time to write an issue.
What i do:
1) Just start FF
2) Open some tabs
3) Open group in the same window
4) Close group
5) All my tabs from step 2 are lost

Video:
https://youtu.be/QYbzmjYbOM0

**Comment by Morikko** [comment]
When you have your tabs on step 2, is the button "Window synchronized" at the bottom left of the menu checked and highlighted in blue ?

If no, your window is not tracked and any change will not be saved.

**Comment by Morikko** [comment]
My bad, I used the old name. Yes it is the "Group (in)visible" button. In next version v0.6.9 it will be only named "Group Visible". 

Is this check-box checked before you switch a group ?

**Comment by mikhoul** [comment]
I had the same issue @Morikko , I've lost many group in the beginning before I understand the purpose of the "Group (in)visible" button. 😜

I've found by myself that if I enable"Group Visible" it save automatically my groups but the name and/or the description is not intuitive for new users IMO.

I would suggest to at least add to the description something like: "When enabled this function will save your current tabs in a group so if you open another tabs group  you will not lose your current tabs".

For the button name maybe something more meaningful like "Autosave current tabs group automatically"  Or maybe something shorter but more meaningful than "Group Visible" for the new users. 😉

Thanks again for this very useful extension :octocat: 

_________________________________________

I will test the new version later today and will comeback on the other issues I was just browsing the issues right now during my lunch.
