### ISSUE TITLE
Request: Having a contextual menu in Chrome to save/send a tab directly in a group.

### ISSUE THREAD

**Issue by mikhoul** [Morikko/sync-tab-groups#115]
Would it be possible with Chromium to use the contextual menu to save a  tab directly in one of the groups ? 

**Ref:** https://developer.chrome.com/apps/contextMenus

Regards :octocat:

**Comment by Morikko** [comment]
From where would you like to see the context menu ? Could you explain a bit more the use case ?

**Comment by mikhoul** [comment]
From any tab I had when "Right clicking" in the page.

Like this if it is possible:

![GitHub Logo](https://i.imgur.com/zpTMCRl.png)

A use case would be I find an interesting page about a project I'm working on and I have already a group of tabs created for this topic so I could just use the context menu to save the current page in the group.

Regards :octocat:

**Comment by marcspc** [comment]
this, please! it would really help for easier management

**Comment by jppmarujo** [comment]
I too, vote for this! :)

**Comment by mikhoul** [comment]
Thanks a lot 👍👍👍

It will save me lot of manipulations to add tabs to the groups when I'm working 😊

Have a nice week-end ! :octocat:
