### ISSUE TITLE
Error caught in Sync Tab Groups

### ISSUE THREAD

**Issue by kartom** [Morikko/sync-tab-groups#116]
Since some update on either sync tab groups or Firefox i keep getting an annoying pop-up in the bottom left corner flashing "Error caught in Sync Tab Groups".

**Comment by jramaex** [comment]
+1
In inport/export settings, the pop-up says "The group list is corrupted... It is impossible to load it". ¿?

**Comment by Morikko** [comment]
Have you already [reported the log](
https://github.com/Morikko/sync-tab-groups/wiki/How-to-help-me-solve-bugs#v068-and-above)
so that I can correct it ?

What is your Firefox version ?

After that can you downgrade to version v0.6.7 (previous), the time the fix
lands ?

**Comment by kartom** [comment]
Firefox version 60.0, and the log file is posted.
How do you downgrade without losing the current tab groups?

**Comment by jramaex** [comment]
After downgrading to v0.6.7, the pop-up not appears, it seems to be a bug introduced in the last version

**Comment by Nionor** [comment]
Same problem here on version 0.6.8 and Firefox 59.0.3 and 60.0

**Comment by Morikko** [comment]
> edit No need to downgrade, I just turned off the "Enable the extension to log errors." to get rid of the error popup for now.

Just be careful, the error might block the save on the disk.
I will fix it tomorrow asap.

> How do you downgrade without losing the current tab groups? 
I don't know :disappointed:  @jramaex
