### ISSUE TITLE
Dragging a tab triggers an error

### ISSUE THREAD

**Issue by itzallan** [Morikko/sync-tab-groups#118]
Whenever I'm in the Groups Manager, click and drag a tab into the "Create new group" row at the bottom of the screen, it triggers an "Unexpected error..." message. It's not a show stopper since I can simply drag the tab into a group that I've already defined, but I thought I would report it. I'm using the latest current version of Sync Tab Groups (2.5.4.1) and Firefox version 60.0 (64-bit).

**Comment by Morikko** [comment]
Thanks, I fixed it. It didn't break the feature but it will be better without needless error message ;)

**Comment by itzallan** [comment]
Wow, that was quick! Thanks! Oh, by the way, sorry about posting the wrong version number, but you figured it out. :)
