### ISSUE TITLE
Extension give spontaneous "Error" message: here's the internal logs

### ISSUE THREAD

**Issue by mikhoul** [Morikko/sync-tab-groups#122]
I was listening a video on another browser and the message from the extension that it have crashed appeared .

Under Chromium and Win7. 
[SyncTabGroups-Log-20180513-230212.zip](https://github.com/Morikko/sync-tab-groups/files/1999257/SyncTabGroups-Log-20180513-230212.zip)

Regards :octocat:

**Comment by Lcstyle** [comment]
Ah yes, I received similar crash as well, about to upload data, but saw yours.  I believe this is also probably related to #110 but cannot confirm.

**Comment by mikhoul** [comment]
@Morikko  OK today I was using Chromium and the "**Error**" happen, it happen when I close Chromium the error message popup:

![image](https://user-images.githubusercontent.com/5678673/40010936-4079d57e-5774-11e8-9c36-a2e81b1a2a2c.png)

Strangely Chromium was running in the background even after I close the windows, so I disabled this "feature/ that I don't need and after the error dit not happen on subsequent close.

Here's the new log attached to help you.
[SyncTabGroups-Log-20180514-123805.zip](https://github.com/Morikko/sync-tab-groups/files/2001805/SyncTabGroups-Log-20180514-123805.zip)


Regards :octocat:

**Comment by Morikko** [comment]
Thanks I will check and correct :)

**Comment by Morikko** [comment]
The wrong error notifications from both files are fixed.
