### ISSUE TITLE
Exception when using with Tile Tabs WE

### ISSUE THREAD

**Issue by peci1** [Morikko/sync-tab-groups#123]
This happened both in 0.6.9 and 0.7alpha, in Firefox 60 64bit on Windows 10.

When I have a single window open with just two tabs in the current group, and activate Tile Tabs WE to split the browser vertically, this exception is thrown. But everything seems to work as it should.

[SyncTabGroups-Log-20180515-013742.zip](https://github.com/Morikko/sync-tab-groups/files/2002951/SyncTabGroups-Log-20180515-013742.zip)

**Comment by Morikko** [comment]
Thank you for reporting. The Error Log is quite recent and might be too strict. So, maybe, it is not a real problem, I will investigate.

**Comment by Morikko** [comment]
Sometimes, Tile Tabs WE opened and closed immediately another extra window. STG was working then on an unavailable window.

Error are better managed when window doesn't exist any more.

**Comment by peci1** [comment]
Not sure if the fix for this bug in 0.7 did not break something else... Now when I close the TTWE layout with 2 tabs split into 2 windows, a third tab gets open displaying the first or second tab from the previously selected group. This tab is not "moved", it is "copied", to say so - it does not disappear from its original group.
