### ISSUE TITLE
group naming / re-naming

### ISSUE THREAD

**Issue by gjwgjwgjw** [Morikko/sync-tab-groups#129]
This extension gets better each version, however the little pen that when clicked enabled a group name to be edited seems to have vanished. I use latest Firefox 60.0.1. Thanks.

**Comment by Angstromm** [comment]
Same issue--missing the pencil that allows us to change/edit group name. I'm on FF 60.0.2 and 0.7 Alpha of Sync Tab Groups. Thanks!!!

**Comment by Angstromm** [comment]
BTW, you can rename a group, for now, from within the Group Manager by selecting the group you want to rename and hitting Ctrl-E, typing in the new name and hitting Enter to accept.

**Comment by gjwgjwgjw** [comment]
Sorry - but that doesn't work for me. Focus
      moves to Ff search box from selected group.
      Thanks,
    
    On 14-Jun-18 8:07 AM, Angstromm wrote:
    
    
      BTW, you can rename a group, for now, from within the Group
        Manager by selecting the group you want to rename and hitting
        Ctrl-E, typing in the new name and hitting Enter to accept.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/Morikko/sync-tab-groups/issues/129#issuecomment-397068529","url":"https://github.com/Morikko/sync-tab-groups/issues/129#issuecomment-397068529","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Morikko/sync-tab-groups","title":"Morikko/sync-tab-groups","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Morikko/sync-tab-groups"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Angstromm in #129: BTW, you can rename a group, for now, from within the Group Manager by selecting the group you want to rename and hitting Ctrl-E, typing in the new name and hitting Enter to accept."}],"action":{"name":"View Issue","url":"https://github.com/Morikko/sync-tab-groups/issues/129#issuecomment-397068529"}}}
      {
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Morikko/sync-tab-groups] group naming / re-naming (#129)",
"sections": [
{
"text": "",
"activityTitle": "**Angstromm**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Angstromm",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Morikko/sync-tab-groups\",\n\"issueId\": 129,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Morikko/sync-tab-groups\",\n\"issueId\": 129\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Morikko/sync-tab-groups/issues/129#issuecomment-397068529"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 341815208\n}"
}
],
"themeColor": "26292E"
}

**Comment by Angstromm** [comment]
Right, same here. But I found, for me, when I open Groups Manager, click on the group name I want to change, hit Ctrl+E, both the FF search box and the group name are highlighted. All you have to do is click back on the highlighted name and start typing...

**Comment by gjwgjwgjw** [comment]
Thanks for that feedback.
      That doesn't work for me. Ff 60.0.2 (64-bit).
        I go to Groups Manager, pick a group from the list, click on it (group opens down to show
        tabs in the group), Ctrl+E and focus goes to the Ff search box,
        click back to group name (focus goes from Ff search box), type but nothing changes in the tab name
        text field. Thanks.
    
    On 14-Jun-18 12:19 PM, Angstromm wrote:
    
    
      Right, same here. But I found, for me, when I open Groups
        Manager, click on the group name I want to change, hit Ctrl+E,
        both the FF search box and the group name are highlighted. All
        you have to do is click back on the highlighted name and start
        typing...
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/Morikko/sync-tab-groups/issues/129#issuecomment-397127647","url":"https://github.com/Morikko/sync-tab-groups/issues/129#issuecomment-397127647","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Morikko/sync-tab-groups","title":"Morikko/sync-tab-groups","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Morikko/sync-tab-groups"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Angstromm in #129: Right, same here. But I found, for me, when I open Groups Manager, click on the group name I want to change, hit Ctrl+E, both the FF search box and the group name are highlighted. All you have to do is click back on the highlighted name and start typing..."}],"action":{"name":"View Issue","url":"https://github.com/Morikko/sync-tab-groups/issues/129#issuecomment-397127647"}}}</!
 script>
<script type="application/ld+json">{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Morikko/sync-tab-groups] group naming / re-naming (#129)",
"sections": [
{
"text": "",
"activityTitle": "**Angstromm**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Angstromm",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Morikko/sync-tab-groups\",\n\"issueId\": 129,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Morikko/sync-tab-groups\",\n\"issueId\": 129\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Morikko/sync-tab-groups/issues/129#issuecomment-397127647"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 341815208\n}"
}
],
"themeColor": "26292E"
}
    
    
    -- 
Gary

Gary Webber
WeDoWebsites.

Internet creations, content management systems, on-line shops & web hosting.

Search engine optimisation - making websites work.
Online Advertising - Google Adwords Certified.

Photography for web & print.

Email: Gary@WeDoWebsites.co.nz
Website: www.WeDoWebsites.co.nz
Tel: ++64 (0)3 528 4044

**Comment by Angstromm** [comment]
Bummber. Oh well, we tried! Hope they fix this soon...much easier the "old" way...

**Comment by gjwgjwgjw** [comment]
Thanks for trying - much
        appreciated.
    
    On 15-Jun-18 9:37 AM, Angstromm wrote:
    
    
      Bummber. Oh well, we tried! Hope they fix this soon...much
        easier the "old" way...
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/Morikko/sync-tab-groups/issues/129#issuecomment-397446536","url":"https://github.com/Morikko/sync-tab-groups/issues/129#issuecomment-397446536","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Morikko/sync-tab-groups","title":"Morikko/sync-tab-groups","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Morikko/sync-tab-groups"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Angstromm in #129: Bummber. Oh well, we tried! Hope they fix this soon...much easier the \"old\" way..."}],"action":{"name":"View Issue","url":"https://github.com/Morikko/sync-tab-groups/issues/129#issuecomment-397446536"}}}
      {
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Morikko/sync-tab-groups] group naming / re-naming (#129)",
"sections": [
{
"text": "",
"activityTitle": "**Angstromm**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Angstromm",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Morikko/sync-tab-groups\",\n\"issueId\": 129,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Morikko/sync-tab-groups\",\n\"issueId\": 129\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Morikko/sync-tab-groups/issues/129#issuecomment-397446536"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 341815208\n}"
}
],
"themeColor": "26292E"
}
    
    
    -- 
Gary

Gary Webber
WeDoWebsites.

Internet creations, content management systems, on-line shops & web hosting.

Search engine optimisation - making websites work.
Online Advertising - Google Adwords Certified.

Photography for web & print.

Email: Gary@WeDoWebsites.co.nz
Website: www.WeDoWebsites.co.nz
Tel: ++64 (0)3 528 4044

**Comment by Morikko** [comment]
Sorry for the late response, Just click on the double arrow. I moved it to a menu for adding some other features (hidden support).

It will be soon replaced with a 3 bars icon.

![capture d ecran de 2018-07-01 17-08-48](https://user-images.githubusercontent.com/7831572/42135856-7509b464-7d51-11e8-92c8-41b80dacbe8e.png)

**Comment by gjwgjwgjw** [comment]
Thanks - works - much appreciated.
    
    On 02-Jul-18 3:13 AM, Morikko wrote:
    
    
      Sorry for the late response, Just click on the double arrow. I
        moved it to a menu for adding some other features (hidden
        support).
      It will be soon replaced with a 3 bars icon.
      
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Morikko/sync-tab-groups","title":"Morikko/sync-tab-groups","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Morikko/sync-tab-groups"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Morikko in #129: Sorry for the late response, Just click on the double arrow. I moved it to a menu for adding some other features (hidden support).\r\n\r\nIt will be soon replaced with a 3 bars icon.\r\n\r\n![capture d ecran de 2018-07-01 17-08-48](https://user-images.githubusercontent.com/7831572/42135856-7509b464-7d51-11e8-92c8-41b80dacbe8e.png)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/Morikko/sync-tab-groups/issues/129#issuecomment-401612931"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Morikko/sync-tab-groups/issues/129#issuecomment-401612931",
"url": "https://github.com/Morikko/sync-tab-groups/issues/129#issuecomment-401612931",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Morikko/sync-tab-groups] group naming / re-naming (#129)",
"sections": [
{
"text": "",
"activityTitle": "**Morikko**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Morikko",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Morikko/sync-tab-groups\",\n\"issueId\": 129,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Morikko/sync-tab-groups\",\n\"issueId\": 129\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Morikko/sync-tab-groups/issues/129#issuecomment-401612931"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 341815208\n}"
}
],
"themeColor": "26292E"
}
]
    
    
    -- 
Gary

Gary Webber
WeDoWebsites.

Internet creations, content management systems, on-line shops & web hosting.

Search engine optimisation - making websites work.
Online Advertising - Google Adwords Certified.

Photography for web & print.

Email: Gary@WeDoWebsites.co.nz
Website: www.WeDoWebsites.co.nz
Tel: ++64 (0)3 528 4044
