### ISSUE TITLE
fails to import FF tabgroups in vivaldi

### ISSUE THREAD

**Issue by leggewie** [Morikko/sync-tab-groups#130]
I recently discovered STG and hope to be using it as a replacement for the now-defunct tabgroups I used to use with FF.  I am running Ubuntu bionic and trying to import the tab groups in vivaldi browser.  It fails silently without any indication of failure but (at least as far as I can tell) no tabs imported.  I prepared a minimal test case for your inspection.

[tabGroups-manual-20180610-161018.json.txt](https://github.com/Morikko/sync-tab-groups/files/2087648/tabGroups-manual-20180610-161018.json.txt)

**Comment by Morikko** [comment]
It is working fine on my session (Chromium). I imported one group 'seagate' with 8 tabs.
I remembered already someone got a problem with the vivaldi browser. I ended by discovering that vivaldi is not exactly working like Chrome.

STG doesn't support Vivaldi.

**Comment by leggewie** [comment]
Importing with Chromium fails too.  At least for my huge 15MB TabGroups json file.  The error log is 34MB long and contains private information.  How can I proceed?

**Comment by Morikko** [comment]
Either you can clean the file yourself to remove the private information or depending the privacy, you can send it to the email address: `synctabgroups@gmail.com` (I am the only owner)

Else, I have no solution.

**Comment by leggewie** [comment]
Here is the error log for another failed import

[SyncTabGroups-Log-20180724-024437.json.txt](https://github.com/Morikko/sync-tab-groups/files/2220643/SyncTabGroups-Log-20180724-024437.json.txt)

**Comment by leggewie** [comment]
I have a dead simple, 2 tab group that fails to import.  Please have a look.
[SyncTabGroups-Log-20180729-010632.json.txt](https://github.com/Morikko/sync-tab-groups/files/2238146/SyncTabGroups-Log-20180729-010632.json.txt)
