### ISSUE TITLE
No group opened on browser start (Firefox)

### ISSUE THREAD

**Issue by galan** [Morikko/sync-tab-groups#134]
Example:
- I have three groups, each has some tabs, group "second"  is OPEN.
- I restart the browser
- No group is active, instead the default tab is open
- If I start creating tabs, and switch to a group, all tabs creating in this context are lost.

Expected behaviour: previous group before restart is opened

Firefox 61.0.1 (64-bit), Addon 0.7.1, Xubuntu 18.04LTS

![1_006](https://user-images.githubusercontent.com/2453957/42553576-acc058ee-84e1-11e8-887f-e2b299868aff.png)

**Comment by Morikko** [comment]
Choose the Firefox preferences: to keep the tabs open from the previous
session.
The group will be matched automatically on start up.

Also, in this state the window is considered as a new one and you have
configured STG to not add it automatically as a group. You can overwrite
this parameter by clicking on the bottom left button. So tabs are going to
be saved during the next switch.

The reason I don't want to over control the Firefox beginning is explained
here: #125.

Have a nice day,

**Comment by galan** [comment]
Hi @Morikko, thanks for clarifying on this issue. Indeed it was missing the "Restore previous session" setting from Firefox.
Thanks for all your efforts on this addon!
