### ISSUE TITLE
Feature request: Side/tool bar groups list display

### ISSUE THREAD

**Issue by vlatkoB** [Morikko/sync-tab-groups#136]
Hello,
I'm wondering if it would be possible to have different ways of displaying the groups list. I mean only group names, without submenu with tabs.
Maybe in a side bar, like vertical tabs extension, or in a toolbar, like bookmarks.

The latter would make it very similar to how Tab Group Manager and Tab Group Helper looked like, and I think it would ease the migration for users of those extensions.

br,
vlatko

**Comment by Morikko** [comment]
Probably duplicates #94 

I won't implement new feature for time availability. PR are welcomed :)

**Comment by comodh** [comment]
can you please add a groups bar at the bottom to show all groups in the same window, without having to open another menu? 
so the bottom bar shows the group and above it you have the regular tab bar that shows the available tabs in the group chosen in the groups bar. the chosen group and tab have a different color...
there was such an extension in FF which improved my productivity significantly but stopped being supported...
if you think about it - what's the point of a tab bar, with so much tabs that you can't recognize which is which... a group tab simply shows which of them to show and thus reduces the tabs shown in the tab bar...
thank you in advance!
Moshe
