### ISSUE TITLE
Loosing and messing tabs in groups

### ISSUE THREAD

**Issue by vlatkoB** [Morikko/sync-tab-groups#138]
I noticed that in one particular group tabs are being removed and tabs from other group opened.
It doesn't happen in a session (changing groups while Firefox is opened), but only after Firefox is restarted (usually the other day, as I have FF open whole day.
I'm using only one FF window and the active option when switching groups is Hide, not Close.
I haven't noticed this in other groups, but I usually open only 3-4 groups out of 17 during a day.

Let me know if I can provide you with some more data.

**Comment by Morikko** [comment]
I know that the logic to remember the association between the hidden tabs and the groups is weak. However, I believe that the tabs are not deleted from the groups but only reopen.

PR are welcomed :)
I might fix bug later on but I don't have much time now.

**Comment by vlatkoB** [comment]
Haven't noticed for a longer time.
