### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mikhoul** [Morikko/sync-tab-groups#139]
I have a question: I use chrome and I have many groups already that I've imported from Firefox.

 My present session/windows have ~windows and I don's see any group created for this session ? 

Here's a screenshot:
![image](https://user-images.githubusercontent.com/5678673/44313732-876c7f00-a3db-11e8-8b21-f24285a3030b.png)

Also I don't see any active group, does I miss something ? 🤔

I'd like that my current windows/groups/session would be saved automatically with my other tabs groups that I have imported from Firefox.

So I'm not sure if I miss something or there is a bug ? 🤔

Regards :octocat:

**Comment by Morikko** [comment]
You can click on the bottom left button in the pop up menu: "Create a new group from the tabs in the window"

**Comment by Morikko** [comment]
![screenshot from 2018-09-20 00-14-06](https://user-images.githubusercontent.com/7831572/45784737-20581980-bc6a-11e8-87c9-78e478f0ae37.png)
