### ISSUE TITLE
stop always reload tabs when switching groups

### ISSUE THREAD

**Issue by scarf** [Morikko/sync-tab-groups#142]
"Tabs opening" is set to "Full"  but would like an option to not reload tabs every time when switching between groups.  tabs should stay open and untouched when switching between groups.  reloading the tabs every time when switching groups causes unneeded network traffic and interrupts other activities for example paused video on youtube, place is lost; form being filled out is lost.  etc.

**Comment by Morikko** [comment]
Select:
 - opening mode: discarded (never load the tab until you click on it)
 - closing mode: hidden (don't close the tab)
