### ISSUE TITLE
How to move tabs? 

### ISSUE THREAD

**Issue by mihalt** [Morikko/sync-tab-groups#145]
Hello! As I understand, after moving to other pc I loose all my tabs. Say me please, is any way to save tabs backups to restore it in other pc?

**Comment by Morikko** [comment]
You can export all the groups from the preferences and import them to the new computer. However, you will only have the groups and tabs reference. You won't be able to keep the living tabs.

![screenshot from 2018-11-26 23-31-01](https://user-images.githubusercontent.com/7831572/49046143-6e8e1980-f1d3-11e8-875f-d3847a4728b5.png)
