### ISSUE TITLE
All Groups Lost

### ISSUE THREAD

**Issue by GThib** [Morikko/sync-tab-groups#146]
All of sudden whilst starting FF the tabs have been empty.
Trying to import tabs from Local Backup - All date-based item opens with error - The list was empty!

Please advice

**Comment by Morikko** [comment]
Usually, when the tabs and the backup are empty, it is because the browser swiped off all your data. Unfortunately, I don't know the reason.

I have planned to change my backend code soon for a more stable version.
I apologize for the inconvenience.
