### ISSUE TITLE
Feature Request: Auto destroy empty groups

### ISSUE THREAD

**Issue by peci1** [Morikko/sync-tab-groups#15]
Now empty private browsing groups are auto destroyed.

What about auto destroying all empty groups (probably as an option)?

When using this addon together with Tile Tabs WE, the number of empty groups can grow quite quickly.

**Comment by Morikko** [comment]
> Now empty private browsing groups are auto destroyed.

This was not really intended except if you set the option to remove groups when private windows are closed. I will check.

> About auto destroying all empty groups as an option

This might be interesting due to the fact that each new window creates a group that is kept.

**Comment by peci1** [comment]
> This was not really intended except if you set the option to remove groups when private windows are closed. I will check.

No, it only happens when I check the new option ;)

**Comment by Morikko** [comment]
Will be in next release with the possibilities of (un)synchronize automatically new window, or force it yourself from the toolbar menu.
