### ISSUE TITLE
Many of my lesser used tabs will not load any more - just moz-extension://87487...

### ISSUE THREAD

**Issue by crakej** [Morikko/sync-tab-groups#150]
So the tabs will not load I just get things like:

moz-extension://753af266-132b-4079-a296-d4ef15657403/tabpages/lazytab/lazytab.html?title=Contact%20-%20Alfa%20Dental%20Ltd%20-%20NHS%20Choices&url=https%3A//www.nhs.uk/Services/dentists/MapsAndDirections/DefaultView.aspx%3Fid%3D26860&favIconUrl=https%3A//www.nhs.uk/img/favicon.ico

The favicons do not load for these pages.  Other pages that I use regularly are ok.  This only seems to have happened in the group I use the most. Hopefully @Morikko can check this out soon - this app is invaluable to me! Hopefully @Morikko will be able to look at it soon.

**Comment by Morikko** [comment]
Maybe the extension has changed his id `moz-extension://753af266-132b-4079-a296-d4ef15657403` and thus it doesn't recover the script to open your page. This is id is managed by the browser.

If it doesn't happen on your new tabs but just on some old ones: you can copy the url parameter.

moz-extension://753af266-132b-4079-a296-d4ef15657403/tabpages/lazytab/lazytab.html?title=Contact%20-%20Alfa%20Dental%20Ltd%20-%20NHS%20Choices&url=**https%3A//www.nhs.uk/Services/dentists/MapsAndDirections/DefaultView.aspx%3Fid%3D26860**&favIconUrl=https%3A//www.nhs.uk/img/favicon.ico

**Comment by crakej** [comment]
I have a LOT of tabs! This did work, but was time consuming.

It does appear to have been fixed - I now get message saying to mousover to load the page and it works.
