### ISSUE TITLE
How to prevent creating new tab groups after ?

### ISSUE THREAD

**Issue by mihalt** [Morikko/sync-tab-groups#159]
Hi! Always when I open new tab in new window, when I close it, it is left as new unnamed tab group. How can I prevent this behavior?

**Comment by Morikko** [comment]
> I open new tab in new window

Are you meaning just opening a new window or something more special ?

Normally, you can select in the extension settings that new window are invisible by default. Then, you have to enable the group in a window manually if you want to do so.

**Comment by mihalt** [comment]
Yes, seems that problem was in New Windows setting. Thank you

**Comment by mihalt** [comment]
And can you answer on this quastion. I am very interested in it too — https://github.com/Morikko/sync-tab-groups/issues/162
