### ISSUE TITLE
Menu unreadable when using a dark theme

### ISSUE THREAD

**Issue by psychoslave** [Morikko/sync-tab-groups#16]
I use the CDL feature of firefox to integrate with the gnome native look and feel with adwaita dark theme. Opening the sync-tab-groups menu display black text over dark background. Here is a sceenshot.

![capture d ecran de 2017-11-21 10-37-58](https://user-images.githubusercontent.com/17067758/33065141-553b0a28-cea8-11e7-8edd-6cbdb5bcf25f.png)

So this extension seems interesting as a tab-groups replacement now that it's gonna with firefox 57, but it's not usable as is for me.

**Comment by psychoslave** [comment]
Ok, I added a few lines to my `~/.mozilla/firefox/xxxxxxxx.default/chrome/userContent.css`

```SASS
/*
sources used to fill this file: 
 https://userstyles.org/styles/90565/firefox-adjust-white-flash-when-opening-new-tab 
 https://userstyles.org/styles/142191/remove-new-tab-flash
*/
@-moz-document url-prefix(about:preferences), url-prefix(about:blank), url-prefix(about:newtab) {
  html, body, #newtab-customize-overlay {
    background: #303030 !important;
    color: #b2b2b2 !important;
  } 
}

@-moz-document url(chrome://browser/content/browser.xul)
{

  browser[type="content-primary"]
  {
    background: #303030 !important;
    color: #b2b2b2 !important;
  }
}

@-moz-document url(chrome://browser/content/browser.xul)
{

  browser[type="content-primary"], tabbrowser tabpanels, #appcontent > #content
  {
    background: #1B1B1B url("chrome://global/skin/media/imagedoc-darknoise.png") repeat fixed !important;
    color: #b2b2b2 !important;
  }
}

@-moz-document url(about:blank),
               url(about:preferences),
               url(about:config),
               url(about:newtab)
{
  #newtab-window,
  html,
  body, 
  #newtab-customize-overlay 
  {
    background: #1B1B1B url("chrome://global/skin/media/imagedoc-darknoise.png") repeat fixed;
    color: #b2b2b2 !important;
  }
}

html>body {
  background: #303030 !important;
  color: #b2b2b2 !important;
}
```

And tada:
![capture d ecran de 2017-11-21 17-16-09](https://user-images.githubusercontent.com/17067758/33083452-b8d22170-cedf-11e7-87a4-3bbf80ce742a.png)

Which is far better than what is rendered inside the Multi-account-container extension menu with the same configuration:
![capture d ecran de 2017-11-21 17-16-20](https://user-images.githubusercontent.com/17067758/33083553-f120d440-cedf-11e7-92bb-9c9ca6c53b5c.png)

I hope this feedback will help you to improve the default rendering you provide.

Thank you @Morikko for your quick reaction in triage.

**Comment by Morikko** [comment]
The application you are showing is not Sync Tab Groups. So the lines you added are for the other extension isn't it ?

**Comment by Morikko** [comment]
- Do you know other extensions that switch between dark and light theme ? 
I am looking for examples.
- Is it done automatically or do you have to set something is the preferences ?

**Comment by ArcturusB** [comment]
I played a little with this behaviour. The Gtk theme appears to be applied automatically to all menus (from Firefox and Sync Tab Groups), regardless of the theme set in Firefox.

Here are three screenshots showing the effect with the light and dark versions of the Adwaita Gtk theme: 

1. **Adwaita:light** Gtk theme, “**Default**” Firefox theme

![stg_bug_light_cut](https://user-images.githubusercontent.com/9514702/33555231-e146dedc-d8ff-11e7-893b-78e1684b7569.png)

2. **Adwaita:dark** Gtk theme, “**Default**” Firefox theme

![stg_bug_dark_cut](https://user-images.githubusercontent.com/9514702/33555227-decb23ca-d8ff-11e7-9af1-fd5fd7c1b2ab.png)

3. **Adwaita:dark** Gtk theme, “**Light**” Firefox theme

![stg_bug_dark_2_cut](https://user-images.githubusercontent.com/9514702/33555223-dbcbba68-d8ff-11e7-9082-5fc64d2a0cac.png)

It would be awesome to have Sync Tab Groups adapt to the Gtk theme, that is for sure. But maybe the first step could be to display the same menu colours regardless of the theme. This way the extension would be usable with any theme.

And by the way, thanks @Morikko for the good work! 🎉

**Comment by Morikko** [comment]
> But maybe the first step could be to display the same menu colors regardless of the theme. This way the extension would be usable with any theme.

This is the easiest and first step.

> The second would be to detect the theme (dark or light) and render the extension in dark or light mode.

Later...

**Comment by psychoslave** [comment]
Thank you everybody for taking time and paying attention to this issue.
