### ISSUE TITLE
Restore pinned tabs

### ISSUE THREAD

**Issue by maddhin** [Morikko/sync-tab-groups#160]
Hi,
Firefox had some issue and came up with the "sorry, this shouldn't have happend message" and lost all tabs. But thanks to STG it wasn't a problem - that is except for the pinned tabs. 
Are the backups of the pinned tabs and is there a way to restore them? I am using every single way to backup tabs but there doesn't seem a way to restore pinned ones. 
Pinned tabs also do not seem to go into other windows although i have this option switched on but this is a different issue (I think).

**Comment by Morikko** [comment]
In STG options, you can set the preference to include the pinned tabs in your groups. Thus, they are closed with a group but also restored afterwards.

**Comment by Morikko** [comment]
I really like this mode as then the pinned tabs are also searchable with the interface.
