### ISSUE TITLE
How I auto-delete groups with contain only an empty new tab?

### ISSUE THREAD

**Issue by signalguest** [Morikko/sync-tab-groups#162]
It's really annoyng that it saves windows with only a new clean tab in it. Why?
![immagine](https://user-images.githubusercontent.com/17174855/53302641-c125b300-3860-11e9-8bc6-f830d3a37c22.png)

I like that new window get a group automatically, but I don't really need to save them if they don't have any content in it except a new empty tab.

**Comment by Morikko** [comment]
Check the solution in https://github.com/Morikko/sync-tab-groups/issues/159 to not track automatically new windows. The fact that non tab windows create a new group is a bug from Firefox. It triggers an event and doesn't tell the kind of window it is.

Another option allows you to remove automatically a group that is empty (not even a new tab). Else you have to remove it manually.
