### ISSUE TITLE
Error caught in Sync Tab Groups

### ISSUE THREAD

**Issue by mw446391** [Morikko/sync-tab-groups#166]
I keep getting an error saying "Error caught in Sync Tab Groups"; also, when clicking on the icon in Friefox, I just what looks like an empty comment box.

**Comment by mw446391** [comment]
![image](https://user-images.githubusercontent.com/5002030/56026830-e2f1d100-5d0c-11e9-95b7-597e3fa59a44.png)
This is the error message that keeps popping up. When I click on it it just opens https://github.com/Morikko/sync-tab-groups/wiki/How-to-help-me-solve-bugs.

    Operating system: Windows 10
    Browser & version: Firefox v66.0.3

When I try to open the Sync Tab Groups Options page, I just get a blank page.

Here is the output from the Sync Tab Groups debug console:

Could not map contract ID '@mozilla.org/widget/printdialog-service;1' to CID {********-****-****-****-************} because no implementation of the CID is registered.
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. background.html
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). background.html:1:42167
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. bg.html
TypeError: tab.sendMessage is not a function[Learn More] bg.js:53:21
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. Configs.js:102
Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionUtils.jsm
Unchecked lastError value: Error: Missing host permission for the tab, and any iframes webextension.js:1
The connection to ws://127.0.0.1:59243/ was interrupted while the page was loading. bg.js:46:17
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
TypeError: tab.sendMessage is not a function[Learn More] bg.js:53:21
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
Unchecked lastError value: Error: Missing host permission for the tab, and any iframes webextension.js:1
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
Unchecked lastError value: Error: Missing host permission for the tab, and any iframes webextension.js:1
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
Unchecked lastError value: Error: Missing host permission for the tab, and any iframes webextension.js:1
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
Unchecked lastError value: Error: Missing host permission for the tab, and any iframes webextension.js:1
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
b is undefined global.min.js:85
Unchecked lastError value: Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. global.min.js:238
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
Unchecked lastError value: Error: Missing host permission for the tab, and any iframes webextension.js:1
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
TypeError: i.a.options is undefined[Learn More] background.js:1:56036
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionUtils.jsm
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
i.a.options is undefined background.js:1
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5
TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17
Error: Could not establish connection. Receiving end does not exist. bg.js:106:5

**Comment by mw446391** [comment]
Let me know, if you need any more info from me. Right now I had to disable the extension as the error is coming up every time your open or close a window or tab.

**Comment by mw446391** [comment]
The error is still happening; even just switching tabs shows the error message. When you click on the Sync-Tab-Groups icon you see just this:

![image](https://user-images.githubusercontent.com/5002030/56190398-0aed7700-6022-11e9-9f4c-98757ac9c19b.png)

**Comment by mw446391** [comment]
I'm still having this problem. Is this a Firefox issues or a problem with Sync Tab Groups?

**Comment by mw446391** [comment]
same issue with

    Browser & version: Firefox v66.0.4 (64-bit)

**Comment by mw446391** [comment]
@Morikko - are you able to provide some initial feedback please? Would be nice to at least know if this is an issue with Sync Tab Groups or Firefox.

**Comment by mw446391** [comment]
it's working again; Sync Tab Groups is still on 0.8.2; Firefox is now on v667.0 (64-bit) and Windows had some major updates recently

**Comment by Morikko** [comment]
The problem is probably here: `TypeError: tab.sendMessage is not a function[Learn More] bg.js:134:17` 

However, I neither use `tab.sendMessage` nor I have a `bg.js` file 🤔

**Comment by mw446391** [comment]
Hmm - I searched my computer and found a `bg.js` here:

`C:\Program Files\Logitech\SetPointP\LogiSmoothFirefoxExt\`

Inside I also found `tab.sendMessage` being used for what looks like a tab refresh:

`                    tab.sendMessage(tab.id, {id: "refreshContent"});`

So it looks like the Logitech SetPoint Firefox add-on is the culprit.

**Comment by mw446391** [comment]
Closing as issue is no longer present.

**Comment by mcitoler** [comment]
Hi @Morikko, the exact behavior describe in the first two comments is happening to me as well.

This is the json file that i get when i download the error log from within the SyncTabGroups settings page:
`{
  "version": {
    "SyncTabGroups": "0.8.1",
    "browser": {
      "name": "Firefox",
      "vendor": "Mozilla",
      "version": "68.0.1",
      "buildID": "20190718161435"
    },
    "os": "linux"
  },
  "logs": [
    {
      "type": "Information",
      "time": "Thu Aug 08 2019 11:51:10 GMT+0200 (Central European Summer Time)",
      "message": "EXTENSION_START",
      "data": null
    },
    {
      "type": "Error",
      "time": "Thu Aug 08 2019 11:51:11 GMT+0200 (Central European Summer Time)",
      "message": "can't assign to property \"title\" on \"L\": not an object",
      "trace": [
        "2/r.mergeObject",
        "/background.js:1:28398 => 1/g.check_integrity",
        "/background.js:1:6089 => 1/g.init",
        "/background.js:1:11446 => "
      ],
      "data": {
        "args": {}
      },
      "fileName": "/background.js",
      "lineNumber": 1,
      "columnNumber": 1
    },
    {
      "type": "Error",
      "time": "Thu Aug 08 2019 11:51:11 GMT+0200 (Central European Summer Time)",
      "message": "JSON.parse: unexpected character at line 1 column 1 of the JSON data",
      "trace": [
        "1/g.getCopy",
        "/background.js:1:3648 => 68/v.createMoveTabMenu",
        "/background.js:1:47608 => "
      ],
      "data": null,
      "fileName": "/background.js",
      "lineNumber": 1,
      "columnNumber": 1
    },
    {
      "type": "Error",
      "time": "Thu Aug 08 2019 11:51:12 GMT+0200 (Central European Summer Time)",
      "message": "g.groups is undefined",
      "trace": [
        "1/g.isWindowAlreadyRegistered",
        "/background.js:1:3569 => b",
        "/background.js:1:75824 => "
      ],
      "data": {
        "args": {
          "0": 1
        }
      },
      "fileName": "/background.js",
      "lineNumber": 1,
      "columnNumber": 1
    }
  ],
  "options": {
    "version": 0.1,
    "privateWindow": {
      "sync": false,
      "removeOnClose": true
    },
    "pinnedTab": {
      "sync": false
    },
    "bookmarks": {
      "sync": false,
      "folder": "Default"
    },
    "groups": {
      "syncNewWindow": false,
      "removeEmptyGroup": false,
      "showGroupTitleInWindow": true,
      "sortingType": 4,
      "discardedOpen": true,
      "closingState": 0,
      "discardedHide": false,
      "removeUnknownHiddenTabs": false
    },
    "popup": {
      "maximized": false,
      "whiteTheme": false,
      "showTabsNumber": true,
      "showSearchBar": true
    },
    "shortcuts": {
      "allowGlobal": false,
      "navigation": true
    },
    "backup": {
      "download": {
        "enable": true,
        "time": {
          "t_5mins": false,
          "t_1h": true,
          "t_4h": true,
          "t_1d": true,
          "t_1w": true
        }
      },
      "local": {
        "enable": true,
        "intervalTime": 1,
        "maxSave": 48
      }
    },
    "log": {
      "enable": true
    }
  }
}`
