### ISSUE TITLE
Please where sync tab group .....

### ISSUE THREAD

**Issue by nameman** [Morikko/sync-tab-groups#167]
where sync tab group  store the groups ?
I installed firefox extended support release on firefox beta, I don't have my groups anymore, why? where are my groups?

**Comment by nameman** [comment]
....on windos 10 ......

**Comment by nameman** [comment]
OK, I have found Storage location .... ONLY in the browser download folder .......

**Comment by Morikko** [comment]
The question has already been asked. Please check among the closed issue. Thank you.
