### ISSUE TITLE
Tab open to local file lost when switching groups

### ISSUE THREAD

**Issue by englishb** [Morikko/sync-tab-groups#17]
Scenario:  I have two tab groups, A and B.  I am currently on tab group B, with one tab pointing to google.com and the other pointing to a local file, E:\test\test.html.  I switch to tab group A, and then back to B, and now B only has one tab pointing to google.com.

Every time I switch groups, all tabs for local files are removed from the tab group.

**Comment by Morikko** [comment]
Firefox API doesn't let me do this: 
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create 
(At paragraph url)

I won't be able while I can't let tabs open when groups are closed.

Sorry.

**Comment by Morikko** [comment]
I have added a custom page for privileged URLs. You can copy the privileged URL and add it yourself in the address bar and load the page.

So you won't lose references to local files.

Warning: those custom pages are closed if the extension is disabled/removed.
