### ISSUE TITLE
Lost current group focus due to browser freezeup

### ISSUE THREAD

**Issue by edfraser** [Morikko/sync-tab-groups#18]
My browser froze so rebooted, then STG created "Unnamed group 8." It should have returned to the same group that was active previous to browser freeze.

**Comment by Morikko** [comment]
Did you have set the Firefox option: "Show your windows and tabs from last time" in part "When Firefox starts" ?

**Comment by Morikko** [comment]
The extension has changed a lot. If you have the same problem on the last version (v0.3 today), just open it again or create a new issue.
