### ISSUE TITLE
Sync Tabs Groups stopped working after Firefox update

### ISSUE THREAD

**Issue by ldm1417** [Morikko/sync-tab-groups#180]
Hello, 
The Sync Tabs Groups stopped working after Firefox update. How to fix? 
Thank you!

**Comment by ldm1417** [comment]
Any response? Could be fixed?

**Comment by Morikko** [comment]
Hello,
Please read: https://github.com/Morikko/sync-tab-groups#the-project-is-no-more-maintained
Alternative: https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/
