### ISSUE TITLE
"Error caught in Sync Tab Groups" window is always running.

### ISSUE THREAD

**Issue by Rafainef** [Morikko/sync-tab-groups#182]
Hi, Morikko, good morning!
My issue is that the "error caught in Sync Tab Groups" window is always running. Most of the times it doesn't matter, but sometimes it difficults to reach information on the right lower part of the screen.
I am using:

> SYN TAB 0.8.1
> FIREFOX 76.0.1 and
> WINDOWS 10 HOME Copia de Evaluación.BUILD 19640 mn_release.200530-1731

I hope this information could help you to solve the problem!
Thank you very much!
Rafael Romero Gamarra.

**Comment by Morikko** [comment]
Hi, thank you for using the extension, unfortunately [the extension is no more devellopped](https://github.com/Morikko/sync-tab-groups#the-project-is-no-more-maintained). I recommend you to use this extension instead: [Simple Tab Group](https://addons.mozilla.org/fr/firefox/addon/simple-tab-groups/).

**Comment by Rafainef** [comment]
Hi!
Ok, thanks for your quick answer. Problem solved.
Thank you very much!
Rafael Romero Gamarra.

________________________________
De: Eric Masseran <notifications@github.com>
Enviado: sábado, 6 de junio de 2020 20:52
Para: Morikko/sync-tab-groups <sync-tab-groups@noreply.github.com>
Cc: Rafainef <rafainef1973@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [Morikko/sync-tab-groups] "Error caught in Sync Tab Groups" window is always running. (#182)


Hi, thank you for using the extension, unfortunately the extension is no more devellopped<https://github.com/Morikko/sync-tab-groups#the-project-is-no-more-maintained>. I recommend you to use this extension instead: Simple Tab Group<https://addons.mozilla.org/fr/firefox/addon/simple-tab-groups/>.
