### ISSUE TITLE
Alternative for Chrome

### ISSUE THREAD

**Issue by v-goncharenko** [Morikko/sync-tab-groups#189]
You suggested alternative for Firefox, but nothing for Chromium - afaik https://github.com/sienori/Tab-Session-Manager works well for such functionality, you may add it to README.

Thanks for this project - I've enjoyed it for couple of years

**Comment by Morikko** [comment]
Thanks @v-goncharenko, I added it. I am glad you enjoyed the extension for so long :tada:
