### ISSUE TITLE
Feature request: Keyboard navigation

### ISSUE THREAD

**Issue by fturcheti** [Morikko/sync-tab-groups#19]
Besides adding keyboard shortcuts like proposed on #8, keyboard navigation would be a handy addition.

My suggestion:

- Up and down arrows: move up and down the list of groups and tabs (if there's some expanded group)
- Space or right and left arrows: expand and collapse focused group
- Enter: activate focused group or tab

**Comment by Morikko** [comment]
Menu window has not automatically the focus when it is opened, it is quite problematic. I will come back to this later on.

**Comment by fturcheti** [comment]
> Menu window has not automatically the focus when it is opened

Didn't know about that, but thank you for attention.

**Comment by Morikko** [comment]
Yes sure, it is still on the road map. I focused first on stability and
performance. Now it is almost done, I will do it soon.

Le 19 févr. 2018 10:20, "Camilo Alejandro" <notifications@github.com> a
écrit :

**Comment by Morikko** [comment]
Navigation Proposition:

General:
 - Down : Next group/tab (or first)
 - Up: Previous group/tab (or last)
 - Insert: Create a new group (accept name with enter)
 - Escape: Close the popup (default behavior)
 - Home: First group
 - End: Last group
 - Page up: Select first tab (if tab selected)
 - Page down: Select last tab (if tab selected)
 - Shift + Page up: Reduce all tabs
 - Shift + Page down: Expand all groups
 - Ctrl + F: Focus the search bar
 - Ctrl + M: Open Manager
 - Ctrl + P: Open Preferences
 - Ctrl + O: Make the group visible/invisible
 - Ctrl + L: change popup size (small/large)
 
Group: 
 - Space: Show/hide tabs
 - Enter: Open the group (or focus)
 - Shift + Enter: Open the group in a new window (or focus)
 - Delete: Close the group (or force)
 - Shift + Delete: Remove the group (or force)
 - Backspace: Undo the close or remove action
 - e: Edit the name of the group (enter to accept) 
 - Shift + Up: Move the group to the position before (if custom sort selected)
 - Shift + Down: Move the group to the position after (if custom sort selected)

Tab: 
 - Enter: Open the tab (or focus)
 - Shift + Enter: Open the tab in a new window (or focus)
 - Space: Hide the tabs and focus the parent group
 - Delete: Close the tab
 - Ctrl + Enter: Open a similar tab in the current window
 - Shift + P: Pin/Unpin the tab
 - Shift + Up: Move the tab to the position before
 - Shift + Down: Move the tab to the position after

Please let me know if you have any suggestion or correction.
