### ISSUE TITLE
Tab order changes after switching current group back and forth

### ISSUE THREAD

**Issue by psisquared2** [Morikko/sync-tab-groups#2]
Hello,

on my computer the order of tabs changes when switching from one group to the other and back. I am not fully sure about the pattern, but it seems to me that the leftmost tab goes all the way to the right, and all other tabs move one to the left after switching to a different group and back. Using FF57, Win 10 64 bit.

Please tell me if you need further information to debug this issue.

P.S. Thank you for the great add-on!

**Comment by Morikko** [comment]
I can't reproduce it on Linux/Window, I tried with 2 groups of 3 tabs.

Do you have more information ?
 - Is it in private window ?
 - Do you have pinned tabs ?

**Comment by psisquared2** [comment]
I tried to analyze this further and I've come to the conclusion that it's related to pinned tabs. To me it looks like the following:

If I have a pinned tab in group B, and I switch from group A to group B then back to A, the tabs in group A rotate (leftmost tab goes all the way to the right, all others go one to the left).

It also seems that if I have two pinned tabs in group B, then the tabs in group A rotate twice according to what I've described above.

I have 14 tabs in group A, none pinned, and 1 pinned tab and two unpinned tabs in group B.

**Comment by Morikko** [comment]
I confirm the bug,  I also received an email about this. I will correct it for the next release ;)

**Comment by Morikko** [comment]
Resolve in 0.1.4

**Comment by psisquared2** [comment]
Thank you for dealing with this issue. I can confirm that it is fixed if the new setting "Synchronize the pinned tabs in groups" is enabled.

However, if you disable the checkbox, the following happens: I have one pinned tab in group A, and (a priori) none in group B. I now switch from group A to B and back to A. As expected, all non-pinned tabs in group A close and those of group B open, and back. However, this process still rotates the non-pinned tabs in group A (and, when I go back to B, also in group B).

**Comment by tigerman** [comment]
Tabs are restored in reverse order.

**Comment by Morikko** [comment]
Sorry for the disagreement. A new fix has been released with 0.1.5.

**Comment by psisquared2** [comment]
Confirmed fixed, thank you!
