### ISSUE TITLE
Close the menu after group is clicked

### ISSUE THREAD

**Issue by mancze** [Morikko/sync-tab-groups#23]
1. Open a group menu.
2. Click a group to switch onto.

Currently the group menu stays open after switching a groups. Extra action is needed to close the menu. It would be actually useful to close the menu after picking a group to open. Or have an option to configure such behavior.

**Comment by Morikko** [comment]
Got it: this behavior makes more sense.

Precision (for me). From same window - Open group -> Close Group.

**Comment by mancze** [comment]
Many thanks!
