### ISSUE TITLE
Feature Request: open group as new window

### ISSUE THREAD

**Issue by allenyllee** [Morikko/sync-tab-groups#24]
Hi :)
I'm very like your extension, thanks for you efforts! 

After working with your extension, I have some request:
Could you make group open as new window?

This is my current work flow:
1. Open firefox, then it will open the last opened tabs, just says it as Group1
2. Currently, If I want to open Gropu2 which I previously saved with sync-tab-groups in a new window, I must open an empty window first, then 
3. Select Group2 in the sync-tab-groups menu

If I can open group as a new window, work flow may simplify:
1. Open firefox
2. Just select Group2 in the sync-tab-groups menu, then it will open group in a new window

With that, I don't actually need hide tabs group function, I can jump between different groups by switching window. I believe that firefox 57 has much more better memory management, even if I open a lot tabs within mutiple window.

Finally, If I can close Group window by just selecting "close" in the sync-tab-groups menu, this whole work flow can finished just through the menu. For completeness, the menu should have two other buttons "close other groups except this group(window)" and "close all groups(windows)".

Best Regards

**Comment by Morikko** [comment]
![Menu](https://user-images.githubusercontent.com/7831572/33263271-78db680e-d369-11e7-887e-a15f2c37ab7d.png)
Click on the +

This is only visible for closed groups, opened ones have the X for closing. This is in the extension since the beginning.

Normally, it should do the trick.

**Comment by allenyllee** [comment]
OK, It's my fault, I didn't notice that, thanks!

BTW, It's about close behavior. When I close the group which window currently opened in foreground, the window just clears all tabs and open the next non-opened group (if no, it'll make a new group).

Is it possible that when I close the current working group, says Group2, it immediately switch to another opened group window, then close Group2's window in the background?

**Comment by Morikko** [comment]
I like this behavior: 
- if other group in other window, switch to it
- else switch to next group in current window

I will do it later, now, it is not my priority
