### ISSUE TITLE
Feature request: Limit add-on width (custom setting?)

### ISSUE THREAD

**Issue by bitkleberAST** [Morikko/sync-tab-groups#29]
If you have a tab with long text in a tab group the add-on gets pretty wide when you open this group. It would be nice if users could customize the max width. Or limit the width in aspect to the browser window. (1/3rd, 1/4th or something...)

**Comment by bitkleberAST** [comment]
Request is already implemented in current version... Close and thanks! :)

**Comment by Morikko** [comment]
Since v0.2.2: size is limited
In v0.2.3: you can switch between small and big window
