### ISSUE TITLE
Expanding large groups makes buttons move horizontally

### ISSUE THREAD

**Issue by psisquared2** [Morikko/sync-tab-groups#3]
Just a minor inconvenience: I have two groups, one with many (~20) tabs, both collapsed. When I expand it, a scroll bar appears on the side that pushes the entire pop-up window to the side, so to collapse the group again I have to move the mouse. Ideally the scoll bar would appear further on the right without the window moving.

**Comment by Morikko** [comment]
I will see if it is possible to correct this. But, it won't be a priority.
