### ISSUE TITLE
UI Issue: Move the Delete Icon and confirmation icon/undo elsewhere

### ISSUE THREAD

**Issue by NeatWolf** [Morikko/sync-tab-groups#33]
Hi, I accidentally deleted a whole group because I accidentally pressed the delete icon.
Then, a "undo" icon appeared in the very same spot.

I clicked it, but it suddenly became another recycle bin. So I totally lost the group.

Closed and reopened Firefox, hoping it wouldn't autosave, but probably I messed it up even more.

I could barely see the rollback icon.

**Comment by JanPokorny** [comment]
I second this, this button design is just plain evil. Relevant screenshots:
![obrazek](https://user-images.githubusercontent.com/4580066/33529559-c6ea6b72-d872-11e7-8983-94d9e00f17b0.png)
![obrazek](https://user-images.githubusercontent.com/4580066/33529563-d2052a38-d872-11e7-8eff-e32cc61f74ab.png)

**Comment by Morikko** [comment]
I never paid attention to it as I am too close to my extension. But yes it is very dangerous. Will be fixed asap.
