### ISSUE TITLE
Feature Request: Session history: store at least 1 autosaved session (all group config) per hour, possibly for a whole week

### ISSUE THREAD

**Issue by NeatWolf** [Morikko/sync-tab-groups#34]

**Comment by Morikko** [comment]
I also already thought at this option. 

I didn't plan to do it as much, but more something like this:
- 5 mins ago
- 1hr ago
- 5 hrs ago
- 1 day ago
- 1 week ago

Also, I will add soon, a menu for selecting which groups to import/export.

**Comment by Morikko** [comment]
A back up system is available for next release (v0.5, coming soon).
You will have to set it in Preferences (Groups section)
