### ISSUE TITLE
null Exception when importing Tab Groups backup

### ISSUE THREAD

**Issue by bitkleberAST** [Morikko/sync-tab-groups#38]
I tried to import my current tab groups backup, but get no response of your add-on and the tabs don't show up anywhere.
When enabling the add-on debugger I can see an unhandled null exception:

11:12:07.263 TypeError: JSON.parse(...) is null
Stack-Trace:
StorageManager.File.importTabGroups@moz-extension://8ff6ce61-0f5b-4753-9365-3a1d24b72d2f/background/storage/filestorage.js:126:10
StorageManager.File.importGroups@moz-extension://8ff6ce61-0f5b-4753-9365-3a1d24b72d2f/background/storage/filestorage.js:55:14
onImportGroups@moz-extension://8ff6ce61-0f5b-4753-9365-3a1d24b72d2f/background/controller.js:175:20
optionMessenger@moz-extension://8ff6ce61-0f5b-4753-9365-3a1d24b72d2f/background/controller.js:267:7
 1 controller.js:186:7
	onImportGroups moz-extension://8ff6ce61-0f5b-4753-9365-3a1d24b72d2f/background/controller.js:186:7
	optionMessenger moz-extension://8ff6ce61-0f5b-4753-9365-3a1d24b72d2f/background/controller.js:267:7

**Comment by Morikko** [comment]
I exported tab groups from the menu of the extension. I have tried: 3 groups on 2 windows with and without session and all work.

Can you send me the content of all of this field: "tabview-tab" under "extData" from your JSON ? Normally, it is the groupID and sometimes if it is active.

**Comment by bitkleberAST** [comment]
It contains the value "null"
It looks like that the value is alsways "null" in "pinned tabs"... :)

**Comment by Morikko** [comment]
Ok, I haven't tried with pinned tabs as in Tab Groups they were never synchronized.
I will try and fix it.

You can either wait or import Tab Groups session without pinned tabs. (Hopefully, it should work)

**Comment by bitkleberAST** [comment]
It's not an easy task to import such a file...
I did unpin my tabs in old FF and created a new backup file, but TabGroups still wrote the null values into the file. I had to open the file with Notepad++ and replace it with a new group name. Don't think this is something a standard user will do/be able to.

**Comment by Morikko** [comment]
It was just an alternative solution for doing it right now. I will fix it for the next release.

**Comment by bitkleberAST** [comment]
Ok, sure. I did not know which intention you had regarding this issue. It could have been that you don't want to fix this as this was a too special usage maybe. Glad to hear that you want to fix it :)

**Comment by Morikko** [comment]
Jajaja too many people could have pinned tabs in Tab Groups, it is really impacting.

Next version will rock:
 - Import pinned tabs in extra group: you can open them from the menu with the + on the tab; then delete the group
 - Import also icons, so imported tabs in closed groups are not naked any more
