### ISSUE TITLE
Sync tabs/groups between 2 machines

### ISSUE THREAD

**Issue by JPFrancoia** [Morikko/sync-tab-groups#4]
Hi,

Thanks for your addon. Since FF 57, I was desperate to find a replacement for tab groups.

I'd like to synchronise my tabs/groups between two machines. One is at work, the other at home.
I noticed there is a file called ```storage.js``` in 

```
~/.mozilla/firefox/6vjpuub7.default/browser-extension-data/sync-tab-groups@eric.masseran
```

If I keep this file syncrhonised between my two computers, would it be enough ? Could there be any conflict ?

Cheers

**Comment by psisquared2** [comment]
I noticed that Sync Tab Groups always keeps a backup of your tabs in Bookmarks -> Further Bookmarks -> SyncTabGroups -> Groups [Backup], so as long as you synchronize your bookmarks via Firefox Sync you are able to access that.

Would it be possible to implement synchronization of tab groups via Firefox's synchronization of bookmarks?

**Comment by JPFrancoia** [comment]
@psisquared2 ok so for now this addon backups the tabs in the bookmark (export), but can't import them ?

I think (but not sure) tabmarks does it: https://addons.mozilla.org/en-US/firefox/addon/tabmarks/

**Comment by psisquared2** [comment]
@JPFrancoia I was suggesting to add this as a feature in the future, right now it is not implemented afaik.

As a workaround, right now you could make a new group, go to the bookmark folder, Open all in tabs, and delete the old group. Be careful about the names of the groups though, I assume the addon will probably overwrite the bookmark folder automatically.

**Comment by JPFrancoia** [comment]
Yep, it will probably work for now, thanks

**Comment by Morikko** [comment]
Some clarifications about the bookmarks: 
- Done only in the "SyncTabGroups" folder
- Remove only "Groups [Back Up] (old)" and "Groups [Back Up]" folders (children included) in  SyncTabGroups 
- As I am only writing the bookmarks, I don't perturb other bookmarks that have the same group names (bookmarks are managed with a specific and unique id for each one)

So, you can copy  the bookmarks (Example: "Groups [Back Up]" -> "Groups") and do the trick from @psisquared2. After, you have to delete it yourself.

Also, you can set the same name for the groups without trouble.

**Comment by psisquared2** [comment]
@Morikko will you look into synchronizing tab groups between computers via bookmarks as a possible feature in the future?

**Comment by Morikko** [comment]
For the sync feature: I already thought about it. The API is providing access to store data with your Firefox account (like your bookmarks). 

I prefer to work with the API as it is more "secure" than bookmarks.

I will work on it soon.

**Comment by Morikko** [comment]
Updates:
 * Bookmarks save can be done in different sub-folders for avoiding overwriting
 * Open the tabs you are looking for yourself from other devices
 * using sync storage could be sensible: limited to 100KB (for people with hundreds of tabs this could be limited)
 * merge open groups on the go is far from easy

For all that reasons, I will let sync feature at this stage and focus more on other features.

**Comment by maddhin** [comment]
I work on two computers with usually the same group names. Will STG be able to distingish between the two computers and make two separated groups of groups or will the groups with the same name "synced" / overwritten?

**Comment by Morikko** [comment]
Groups are for now only local on your computer.

However, you can save all your groups as bookmarks. In preference, you can:
 - do a dave manually
 - or save automatically

The save is placed in SyncTabGroups folder, by default in other bookmarks. A save is done in a subfolder with the name you have set in preference. By default, the name is default. If you use different computers on the same Firefox account, just set a different subfolder name for each.
Thus, Your save won't be overwritten, and you will be able to find again your tabs from other devices.

**Comment by leggewie** [comment]
Thank you VERY much for this extension.  Like so many others, I'm pulling my hair out over the mess that FF created with the webextension mess.  I am considering to ditch FF and move to chromium.  Is it possible to share tab groups between Chromium and FF, even as a one-time import?
