### ISSUE TITLE
Tab content disappearing (Problem with imported Tag Groups extension)

### ISSUE THREAD

**Issue by maddhin** [Morikko/sync-tab-groups#40]
Hi,

when I switch between groups, pinned tabs just disappear. This might be caused by the fact that I just imported groups (from Tab Groups file) and the pinned tabs were just in one group. 

But besides the pinned tabs, "normal" tabs are also getting lost when switching between groups. Sometimes only a few, sometimes all of them. The tabs itself do not disappear but the content - the tabs are just shown as empty tab ("new tab"). 

There is also a bit weird behavior of new unknown groups being generated with a - what seems like - dublicate of (the last opened?) group. 

I also lost all groups/tabs after a restart of Firefox...

I wish I could be more precise and will post if I find some pattern.

Running latest Win10.

**Comment by maddhin** [comment]
hm, I just lost all tabs of a group again. 

I have ~15-20 groups with 5-50 tabs inside (~250 tabs total), plus this "import folder" which containers all tabs again (~250 in one group). I guess this confuses STG and causes all kind of funny behavior - when I open the bookmark folder, I can literally see the bookmark groups appearing. 

I'm probably going back to FF56 for now - otherwise I can't get much work done during the day haha

But absolutely brilliant plugin - will be happy to help debugging!!!

**Comment by Morikko** [comment]
Sorry for the disagreement. It would be better if you wait a bit. An issue has already been opened: #38.
I haven't paid attention to pinned tab in Tab Groups export file.

> I also lost all groups/tabs after a restart of Firefox...

Groups were removed or your windows not synchronized any more with the dedicated groups ?

> when I open the bookmark folder, I can literally see the bookmark groups appearing

Disable the bookmark auto-save in preferences, it will be next default behavior by the way. Bookmarks creation is really heavy: long and high CPU cost. On top of that, I implemented an easy and basic behavior: complete bookmarking at each save. So with your 250 tabs, it is probably a blast.

After small fixes and groups/tabs reordering, it will be the next feature I will improve.

**Comment by maddhin** [comment]
no worries, happy to help making this work.

> Groups were removed or your windows not synchronized any more with the dedicated groups ?
complete loss of all groups except for one called "unknown" if I remember correctly. This actually happend when I opened Firefox for the second time after importing the Tab Group groups. The first restart went without problems. But the next time all was gone. It is possible STG didn't finish something as I had FF running for ~15min only but such a loss ist hard. 
But almost easier to repair (I did a new import) as just repairing a bunch of tabs that got lost in a single group. That is really annoying:) 

> Disable the bookmark auto-save in preferences
will try this. Although I am switching between 2 computers during the day, so a sync of the groups would be the feature I am praying for haha

**Comment by Morikko** [comment]
> This might be caused by the fact that I just imported groups (from Tab Groups file) and the pinned tabs were just in one group.

You succeeded to import pinned tabs ? I just got null exception like #38

**Comment by maddhin** [comment]
> You succeeded to import pinned tabs ? I just got null exception like #38 

haha - I almost spilled my coffee over the laptop bursting out laughing!! I think I did but will pay more attention when I go back to FF57 tomorrow... :) 
I think it did import the tabs but not in pinned state, just as unpinned tabs.

**Comment by Morikko** [comment]
Ok ok, but it will be better if you wait v0.3.1.
It will fix pinned tabs problem import.

**Comment by Morikko** [comment]
Could you try again on v0.3.1, with bookmark auto-save disabled. Thanks

**Comment by elizabethsimon** [comment]
I also had a complete loss of all groups (except for one Unnamed group 0) the group that remains contains the tabs that were open when I closed Firefox.
Unfortunately since the tabs appeared to be the same as the last time I used FireFox, I did not noticed that the other groups were gone until I tried to switch groups. Needles to say I was NOT happy that the other groups (with over 100 tabs) were missing.

This has only occurred on one computer that I know of (unfortunately the one with the most tab groups). 

The last that I know the groups were there was a week ago shortly before I shut off the computer for most of a week. So is it possible that groups disappear when the computer is off? Or maybe updates that happened when I restarted?

**Comment by Morikko** [comment]
Sorry for the inconvenience @elizabethsimon, I am on your problem. It might be more liked #44 than this thread that is a typical case of bad effect of bookmark auto-save.

Thus, I will continue the discussion on the other one. I added a note, I have an idea of the source of the problem.

> So is it possible that groups disappear when the computer is off? Or maybe updates that happened when I restarted?

No, the application has failed somewhere.

**Comment by Morikko** [comment]
Since v0.4.1: bookmark auto-save disabled; Next version will be totally different.
