### ISSUE TITLE
"Sync Tab Groups"-Tab opens...

### ISSUE THREAD

**Issue by foreachthing** [Morikko/sync-tab-groups#45]
I don't know when or why, but this tab
`moz-extension://bb8fe090-c8c8-4b6a-8bb4-f7a14da9ea66/pages/priviledged-tab/priviledged-tab.html?title=Add-ons+Manager&url=about:addons&favIconUrl=chrome://mozapps/skin/extensions/extensionGeneric-16.svg`
opens (to me) at random. Mostly when switching tab groups.
Screenshot of the page:
![image](https://user-images.githubusercontent.com/10420187/34045870-28746866-e1ab-11e7-8255-41c0ee60485e.png)

What is that? Where does it come from? How can I disable this _feature_?

**Comment by Morikko** [comment]
This is because STG can't open "about:..." url. I never open "about:addons" except if you had it in your groups when it was closed.

Don't you have another addon that opens this URL ?

**Comment by foreachthing** [comment]
Gotcha! Whenever I have a tab "about:..." open, STG can/will not save this and then display the message above. Since I'm still testing FF57, I'll leave tabs open all over the place. Again, thank you for your time and sorry for wasting it.

**Comment by Morikko** [comment]
Actually, it is always the same message but it reminds you the specific URL
where you were before. Just click on the blue button to copy the url and
you can paste it yourself in the URL bar.

It is especially useful if you are working on local files, you don't have
to seek again the path.
