### ISSUE TITLE
Tab order not respected

### ISSUE THREAD

**Issue by foreachthing** [Morikko/sync-tab-groups#46]
Not much else to say. Whenever I switch from one group to another, I am pretty certain, that the order is not kept the way I left it.
If you need more info, please let me know.

One thing I just found: if the second tab (from the left) was selected, then group changed and back, then the previously second tab becomes the first tab.

**Comment by foreachthing** [comment]
Dang it! I thought I test them all! 
I think "Tab Open/Close Control" -> https://addons.mozilla.org/de/firefox/addon/tab-open-close-control/ is causing this behavior. Sorry to bother you!
OS: Windows 7 and 8.1.

**Comment by Morikko** [comment]
You are not the first one surprised ;) I am glad you found it.
