### ISSUE TITLE
Sort Field in Settings, drop down dialog screen positioning wrong

### ISSUE THREAD

**Issue by Lcstyle** [Morikko/sync-tab-groups#47]
Please review the following screenshot:

![si-06-04-21-pm_0022](https://user-images.githubusercontent.com/1028272/34063877-0269060a-e1c3-11e7-9703-97494bcaf343.jpg)

I thought this was just a fluke, so I restarted and tried again.  Issue seems to be reproducible.

**Comment by Morikko** [comment]
I also saw it recently on a friend's computer. 

Are you on windows ?

**Comment by Lcstyle** [comment]
Yes. Winblows 10

**Comment by Morikko** [comment]
I just tried with the last release. It was working well.

I will close it. When the next release will land (soon), if you come across again, just open it again.

**Comment by Lcstyle** [comment]
fix is confirmed.
