### ISSUE TITLE
Help ..SAVED TAB GROUPS ARE SPARIED

### ISSUE THREAD

**Issue by nameman** [Morikko/sync-tab-groups#49]
I had created some tab groups for a few days everything worked perfectly.
Today the saved groups have all disappeared !!! and I can not even create others !!

This extension in which folder saves the tab groups?

Thanks for your help

**Comment by nameman** [comment]
my tab groups are tuned after in Settings> Privacy and Security> Modules and Password I have reclaimed on Remember login credentials that was no longer selected I do not know why .....

**Comment by Morikko** [comment]
That is weird you can't create any other one. However, I don't know about the effect of privacy settings.

The extension never changes nothing in global settings. I don't know if login can have an impact on the extension behavior.

**Comment by nameman** [comment]
Maybe it was just a chance that I found my groups after selecting Remember login credentials in privacy & security .....
However, before my groups were gone ....

Sorry, but where are the groups saved on the disk? ... in which folder?

Thanks for help

**Comment by Morikko** [comment]
See https://github.com/Morikko/sync-tab-groups/issues/32#issuecomment-350467362
