### ISSUE TITLE
FeatureRequest: Load Only when activated with a click

### ISSUE THREAD

**Issue by cyberpunkbln** [Morikko/sync-tab-groups#5]
Hello,

is it possible that the activation of an group don't load all tabs? And only the open tab was loaded?

is it possible to sort the groups per drag and drop?

thx
cool

**Comment by Morikko** [comment]
Nice idea! However, it is not available now:

[Support the "discarded" property inside browser.tabs.create()](https://bugzilla.mozilla.org/show_bug.cgi?id=1378647)
[Implement tabs.discard method for Desktop](https://bugzilla.mozilla.org/show_bug.cgi?id=1322485) (In Firefox 58)

I will wait the first thread to be solved. Else, I will try to cheat with the second one but only when Firefox 58 will arrive.

**Comment by cyberpunkbln** [comment]
Hello,
thx. Ah i understand only fully activated loaded tabs are supported in the moment from the render-engine. But at the moment i must say that firefox quantum very very good discard closed tabs, a good garage collector, when the new fearures comes in the api it will be greater for an extension like yours.
greetz

**Comment by fturcheti** [comment]
Hi, Morikko, 

take a look at this workaround: https://bugzilla.mozilla.org/show_bug.cgi?id=1378647#c17

I have not tested that specific add-on, but I have seen this kind of workaround before. I don't know if it something simple to add to your extension until the proper API method is available, so I'm just reporting this possible temporary solution for your evaluation.

**Comment by Morikko** [comment]
I have already heard about it. It looks interesting and it is very similar to the way I do with privileged URLs. However I faced an issue, when the extension is disabled (thus during update), all the extension URLs are closed immediately. And all the tabs that seem discarded are extension URLs.

I just tried: 
 - It is faster but not too fast as Firefox still opens a local tab
 - Every "discarded" tabs are closed when the extension is disabled
 - The listener for doing clean up before exiting is not working now ([Documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onSuspend))

Sorry, I won't implement such a risky feature.

**Comment by cyberpunkbln** [comment]
Hello,

but what i understand is that it gives 2 not risky choices:

1. Firefox resolves this in the future automaticly with the old mechanism in modern,
2. Firefox attach the ability to the new APi that Tabs has states like loaded or not loaded or something without a hack and you implement it.

Support the "discarded" property inside browser.tabs.create()
Implement tabs.discard method for Desktop (In Firefox 58)

I hope it will come. I understand Mozilla that the new Firefox way are an hard way.

Yes you are right no hacking feature.

At the moment i can only use some Tabs and no hundred like before;).

**Comment by Morikko** [comment]
Finally, I checked again the code in order to see if I can keep the tabs open and I can :)

So, next release will include a home made discarded mode. Also, privileged URL replacement tab are not closed any more!

Sorry for taking so long time for understanding why... 

Of course, when FF will release an official method, I will switch to it.

**Comment by duttyend** [comment]
Thanks a lot, you're awesome !
