### ISSUE TITLE
Order

### ISSUE THREAD

**Issue by aurelienroussel** [Morikko/sync-tab-groups#51]
Hello,

The opening tabs are not reopen in the correct order.

It's sometimes difficult to organize it again.

Not a big bug just a plus to make it happen.

Thank you

**Comment by Morikko** [comment]
Can you check that you don't have another extension that is disturbing the tabs opening ?

This bug has already been corrected and validated. Since, I only got wrong bug from people due to other extensions changing the order.

**Comment by aurelienroussel** [comment]
![extensions](https://user-images.githubusercontent.com/22716137/34453756-8f570f4a-ed5c-11e7-8bfa-83b4455d0450.png)

**Comment by Morikko** [comment]
Open Tabs next to Current, Maybe
