### ISSUE TITLE
Mooving the group like a folder

### ISSUE THREAD

**Issue by aurelienroussel** [Morikko/sync-tab-groups#53]
Hello,

Could you add the possibility to moove / reaorganize the order of the group like folder by clic and maintain ?

Or by using arrow don and up when we access to the editing menu ?

Thank you

**Comment by Morikko** [comment]
In Preference, In Group section, select Groups Order: "Custom".
Then, you can drag & drop groups from the menu to change their positions.

**Comment by aurelienroussel** [comment]
Personnaliser en français. ;) Merci
