### ISSUE TITLE
The "+ tab" is mooving

### ISSUE THREAD

**Issue by aurelienroussel** [Morikko/sync-tab-groups#54]
Hello,

The + tab to add a tab is mooving...

![screenshot_444](https://user-images.githubusercontent.com/22716137/34531302-207e084a-f0b2-11e7-9dbc-7407cf04367b.png)

@+

**Comment by Morikko** [comment]
Where is the screenshot taken ? In the menu, the tabs are the ones below the other ones

**Comment by aurelienroussel** [comment]
It's in the top menu of tab.

![screenshot_20](https://user-images.githubusercontent.com/22716137/34531199-d9789e42-f0b1-11e7-80dd-d240b855d0fd.png)

In this sreenshot, it's normal.

**Comment by Morikko** [comment]
It is not this extension that adds the +. Sorry

**Comment by Morikko** [comment]
The extension DIDN'T add button in the tabs bar. #55
