### ISSUE TITLE
Feature Request: Possibility to assign a different proxy for each group and / or tab

### ISSUE THREAD

**Issue by nameman** [Morikko/sync-tab-groups#57]
Would it be possible to assign a different proxy for each group and / or tab?
It would also be interesting if a tab is busy with a proxy for example for a download, changing tab or group the download continues with the default proxy while the new tab / group uses a different proxy .... but maybe I ask too much ... ... :)

**Comment by Morikko** [comment]
I won't add proxy support in a close future. You might check other extensions that can support proxy change for windows (more or less a group) or tabs.
