### ISSUE TITLE
blank tabs

### ISSUE THREAD

**Issue by Butch-O** [Morikko/sync-tab-groups#58]
when I opened today, 3 of my 5 groups had the correct number of tabs open up, but all were blank (New tab).  2 of my groups opened as normal.  Advice?  Thanks

**Comment by Morikko** [comment]
Wow totally crazy. I have never seen this.

- Are you on windows ?
- Did it happen once only or is it happening frequently ?
- Did your groups be updated ? Did you see New Tab in the Menu ?
- Have you checked the browser console for error messages ? (Ctrl+Maj+J)

**Comment by Morikko** [comment]
Without further information, I can't do anything. If the problem occurs again, you can reopen this discussion.
