### ISSUE TITLE
Improve behavior of groups in private mode

### ISSUE THREAD

**Issue by psisquared2** [Morikko/sync-tab-groups#6]
If you open a new private window, a new tab group is automatically generated (as desired). If you close this private window, the group persists. I would expect that group to get deleted automatically, as (according to Firefox) only bookmarks and downloads should persist. If this is the desired behavior, I would like to at least have the option to automatically delete tab groups from private windows.

**Comment by Morikko** [comment]
Nice idea! I was thinking about an option to let private window out of the sync but this option is good as well.

**Comment by TRSyntax** [comment]
@psisquared2  👍 

yeah. i just figured out the hard way, and ended up in a pretty weird situation to say the least.
and i wanted to add that for those who have set their browser to `'Always use private browsing mode'`, this could be a real annoyance. but with this option, both yours, theirs and my problem would be solved.

@Morikko 

i would also like to see the option to `'Hide designated groups in accordance with browsing mode`' so that i cannot see my private groups in "normal browsing" and vice versa with "private browsing". just with a flashy warning like:

> "When enabling this, private session data will be saved locally!"

also, in future development of your add-on, you now have the option to make encrypted session databases for private sessions. that would be new and intriguing  👍

**Comment by psisquared2** [comment]
@TRSyntax separating the groups by private and normal windows sounds like a good idea!

I guess as a quick fix one could implement the deletion of private groups on closing, in the long term it might be better to just keep the private groups in memory and not put anything from private mode on the HDD at all. That would also ensure that private groups get deleted if Firefox crashes.

**Comment by peci1** [comment]
I just wonder how the addon could have passed Mozilla review process... I like the addon (since it's the best for now until tab hiding API is released), but this issue seems pretty bad to me. Please, fix it asap.

**Comment by Morikko** [comment]
As a first goal, I will add those features (requested from the title):
 - Choice if private window are sync
 - Delete automatically groups from private window when closed

@TRSyntax Once, this will be done, I will study more how to improve the private mode session in the addon. Your idea looks interesting.

> also, in future development of your add-on, you now have the option to make encrypted session databases for private sessions. that would be new and intriguing

I will have a look on this.

**Comment by Morikko** [comment]
[Update]
In 0.1.4 ( see extension options)
 - remove group on close private window
 - don't sync private window 

Further possibilities:
 - keep private groups only in memory/don't save on disk (will be done)
 - separate strict  (not a priority)

**Comment by peci1** [comment]
Thanks.

**Comment by psisquared2** [comment]
Hi,
as of version 0.2.2, the option "Synchronize each private window as a new group" does not seem to do anything. Whether enabled or not, a new group is created for each private tab. Besides, I don't think this description is not very clear. Would it be possible to relabel it to "Enable synchronization of private windows" and fixing the behaviour?

**Comment by Morikko** [comment]
I changed the label in v0.2.3, is it better ? 

Are you speaking about each private tab or window ?

**Comment by psisquared2** [comment]
The label is definitely better. Concerning the behaviour:
What confused me a bit is that if my settings are "A new window creates a group automatically" : on,  and "New private window creates a new group" : off, opening a new private window still creates a new group. However, as I now realized this group does not synchronize any tabs (as desired). I would have expected that no group is created in the first place, though the current state does not show any undesired (but merely mildly confusing) behaviour.

**Comment by Morikko** [comment]
@psisquared2 I did some changes in v0.3. 

Normally, the behavior of new private window is now totally decorrelated from new normal window.

**Comment by psisquared2** [comment]
Thank you! Now it does what I'd expect it to do in all settings.

**Comment by Morikko** [comment]
In next release: Private Windows (PW)
 - PW are temporary
 - PW are only visible in the Menu for convenience (transferring tabs and changing focus easily)
 
Private windows behavior:
- Still an Option for the default state (Visible/Invisible in the Menu) of new Private Windows (PW)
- Still the button for changing the state (Visible/Invisible in the Menu) from the Menu while being focusing the window
- Change about the behavior:
  - PW are not exported/saved on the disk
  - PW closed are always removed
  - PW don't survive a browser restart
  - PW are visible in Purple in the Menu 

Thanks all for your ideas. If something looks weird, don't hesitate to respond.

**Comment by psisquared2** [comment]
Thank you for version 0.5!

Drag and Drop of private tabs into non-private groups doesn't work for me. I don't use the feature, but I thought I'd report it anyways.

Following setup:
1) Open a regular window with group A and a private window with private group B.
2) Open a website X in group B.
3a) Drag & Drop X onto the label "group A" while it is not expanded.
Then I get a new tab in group A instead of website X. Also, website X doesn't close in group B.
3b) Drag & Drop X into the expanded group A (e.g. below an existing tab in group A).
Then nothing happens at all.
3c) Right click on tab -> Move to group does the same as case 3a).

On a side note, thank you for implementing discarded tabs right for the release of FF58! This makes the extension a *lot* better.

**Comment by Morikko** [comment]
See #70
