### ISSUE TITLE
Alt+Shift+Space shortcut does not work.

### ISSUE THREAD

**Issue by chinook77** [Morikko/sync-tab-groups#61]
Hi, Alt+Shift+Space on Windows 10 opens the OS context menu instead of "Open Sync Tab Group Menu". Can I modify that shortcut assignment?

Thanks in advance.

**Comment by Morikko** [comment]
Nop, shortcuts are hard coded in the config file. Thus, it is not flexible.

However, I have found nothing about this shortcut (Alt+Shift+Space) on windows.
Did you add it yourself or with a program ?

**Comment by chinook77** [comment]
![screenshot 11 _li](https://user-images.githubusercontent.com/19517348/34964177-117bad20-fa2b-11e7-90bf-92dd10a7003f.jpg)

I didn't do any modification, the upper left menu marked on the screenshot is activated by that shortcut combination.

**Comment by Morikko** [comment]
I have found something: it is actually only the shortcut Alt+Space.
So, you confirm me it is triggered even if you press Shift on top of Alt+Space ?

I am thinking about how to redesign shortcuts. I will change the shortcuts soon (#8).
Actual ones for switching groups can conflict with text selection.

Else, you have a [method for disabling the shortcut.](https://superuser.com/questions/61069/how-can-i-disable-selected-windows-7-keyboard-shortcuts)

**Comment by Morikko** [comment]
I assigned Ctrl+Shift+Space for next release (coming soon v0.5):
 - Easier to do with one hand
 - Will solve the Windows Incompatibility

**Comment by chinook77** [comment]
Nice, excellent  add-on.
