### ISSUE TITLE
Tabgroups are lost if computer crashes or reboots - Now Permanently!

### ISSUE THREAD

**Issue by crakej** [Morikko/sync-tab-groups#62]
Tabgroups are lost after some crashes/reboots. I can reproduce this by powering off my PC (Win 10).  I then have to recreate them from the bookmarks so lose anything new I haven't specifically bookmarked before the crash.

My PC is a Ryzen build, and does crash regularly when trying to OC ram, but it can also happen from power loss.

I'm now in a position where I can't create groups at all and it's not creating them automatically when I open a new window, so I've lost ALL functionality.
![nogroups](https://user-images.githubusercontent.com/35423399/34916304-03ff9600-f92e-11e7-958f-9bb4ce1ea4c2.JPG)
This is what it looks like after I create a new group and give it a name.

I should add that I have tried removing the add-on and re-installing but still doesn't work. Also disable and re-enable, same result. Something does appear to be in the export file which I'm happy to fwd to you, but it does NOT contain all my group names or URLs.

The file storage is now called storage.js-xx.corrupt, there are many of these up to xx=13.  All of these files contain nothing but NUL chars.

**Comment by crakej** [comment]
I have just found a curious work-around which has allowed me to recreate my groups. I just un-clicked the Window Synchronized box and hey presto I could create groups and re-populate them.  I don't even know what that checkbox does, but after restarting FF, it was checked again and my recreated groups are there.

Hopefully this info will be helpful for you to introduce some kind of protection from reboots.

**Comment by Morikko** [comment]
Normally, Groups shouldn't disappear even with restart or reboot. Also, have you seen #48 ? It is just that Groups are not appearing in the Menu. At the end, Did you find back your groups or just the recreated ones ? 

> Tabgroups are lost after some crashes/reboots. I can reproduce this by powering off my PC (Win 10).

Is it at each reboot ? Or randomly ?

> The file storage is now called storage.js-xx.corrupt,

This is quite strange. It even seems it is a Firefox core error. Have you checked if there were messages in the browser console ? (Ctrl+Maj+J) 

> Something does appear to be in the export file which I'm happy to fwd to you, but it does NOT contain all my group names or URLs.

What do you mean by this ? Have you tried to import it back ?

> Window Synchronized box 

If unchecked: your window is invisible
If checked: your window is a group, if you checked, a new unnamed group is created with the tabs in the current window

**Comment by Morikko** [comment]
This could be related to your situation: [comment](https://github.com/Morikko/sync-tab-groups/issues/48#issuecomment-357933465).

However, in my case, the save on the disk was not corrupted.

So maybe, your problem might be caused by Firefox core when it is saving your groups on the disk and your computer is crashing.

**Comment by jonfre** [comment]
Same problem. Tab group list empty. But they exist in bookmarks > Tab groups.

I can't create groups regardless of _Window Syncronized_ checked.

When I type a new group name, the following error displays in the console:
_TypeError: title is undefined_
Maybe you found this in #48 .

Firefox 57.0.4
Sync Tab Groups 0.4.1

**Comment by Morikko** [comment]
Update with version 0.5: 
 - Corrupted data is watched and is corrected (if possible)
 - An automatic back up is provided, then you can import the back up back.

Can you let me know if you face again the problems in the next days ?

**Comment by jonfre** [comment]
9 groups, so far no problems!

**Comment by crakej** [comment]
Many thanks - all seems to be working really well. I think this was at least in part caused by some problems with FF57.
