### ISSUE TITLE
Tab hiding support

### ISSUE THREAD

**Issue by hdd60311** [Morikko/sync-tab-groups#64]
A preliminary support for it has been added in firefox 59.
https://bugzilla.mozilla.org/show_bug.cgi?id=1423725

**Comment by Morikko** [comment]
I will check soon !

**Comment by hdd60311** [comment]
Any news about this?

**Comment by Morikko** [comment]
I started work on this. It will land before FF59 becomes a stable release (Mid-March).

There will be 2 modes:
 - Keep tabs alive and visible (Chrome and FF)
 - Keep tabs alive and hidden (FF59+ only)

**Comment by saleem-git** [comment]
Hi,
The add-on still reloads the tab when I switch between groups. Firefox gave me this add-on https://t.co/x1Hm0751a8, it just a concept add on but it hides and un-hides tabs without realoading them.

**Comment by Morikko** [comment]
I am still on this, however I prioritized stability last days. When a version will be available, I will create a beta for test. I will need help from you for this.

**Comment by peci1** [comment]
Let me know then, I'll join the beta tests. Thanks!

**Comment by Morikko** [comment]
I have been able to hide/show a group and it's pretty fast!
However before landing a beta, I want:
- [ ] Test to guarantee it is always working
- [ ] How to deal with not hidable tab
- [ ] Keep the reference after a browser restart 
- [ ] How to manage the hidden tabs with the UI

Also, a bad news, FF doesn't allow to discard tabs that has a before unload event. And, websites often use it. See [1420681 - Add forceDiscard property to tabs.discard](https://bugzilla.mozilla.org/show_bug.cgi?id=1420681)

**Comment by Morikko** [comment]
![hidden_tabs](https://user-images.githubusercontent.com/7831572/38707311-2f864d3c-3eb1-11e8-89be-88631f329c23.gif)

**Comment by peci1** [comment]
Like at the old times with Panorama!

**Comment by Morikko** [comment]
[Last news](https://github.com/Morikko/sync-tab-groups/wiki/Hiding-support) on April 15th

**Comment by Morikko** [comment]
Finally, the [first version is available (v0.7-alpha)](https://github.com/Morikko/sync-tab-groups/releases/tag/v0.7-alpha). It is NOT a final release, so bug can still appear:
 - Hidden tabs might be lost -> don't let temporary data
 - Groups can be damaged -> be used to the back up system

For avoiding those problems, you might test it [on another profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) that will be completely unrelated to your current session.

Read carefully the [hiding documentation](https://github.com/Morikko/sync-tab-groups/wiki/Hiding-support) before trying it. Also, you need to activate the hiding option in Firefox.

Installation step:
1. `xpinstall.signatures.required` preference in about:config should be set to false
1. Download the XPI file
2. On the top bar in Firefox select: File > Open A File
3. Select the XPI file and accept the installation

I am waiting for all your feedback. :smiley: :+1:

**Comment by peci1** [comment]
Thanks. The xpinstal.signatures.required option is only available in Firefox developer edition. In regular firefox, you need to sideload the addon via about:debugging.

**Comment by peci1** [comment]
Otherwise I haven't noticed any problems so far (except the addon opening two tabs whose content cannot be loaded right after activation).

The tabs are: 

    moz-extension://ea27fc28-4df4-41ac-9a8d-7f02af900a47/tests/test-page/integration.html
    moz-extension://ea27fc28-4df4-41ac-9a8d-7f02af900a47/tests/test-page/unit.html

**Comment by Morikko** [comment]
Experimental API in the next release :+1:

**Comment by Morikko** [comment]
Since Firefox 61, it is an official feature. So, I close the issue as it is also well implemented.
