### ISSUE TITLE
Update "About this extension" on the add on page

### ISSUE THREAD

**Issue by lucas-mancini** [Morikko/sync-tab-groups#65]
On this site: https://addons.mozilla.org/en-US/firefox/addon/sync-tab-groups/, the description on the "About this extension" section is kind of updated, a few things I've noticed:

- _This extension is really young (2 weeks) and often changes._  - is no longer true.
- We now have Spanish translation and it is not listed on the **Languages** section.

**Comment by Morikko** [comment]
I just dropped the release last Sunday for finally having all the new features. But I haven't the time to update the information as I want to do some deeper changes.  (I will do it this week)

 - The Extension Page (Basic description, and specific information about the behavior in Firefox)
 - A dedicated website is under creation (Description, video example and guide of all the features)
 - The README (Basic description and developer information only)

> This extension is really young (2 weeks) and often changes. - is no longer true.

I don't really know as I will work again on shorter road-map but for sure I don't want to change the UI/UX a lot. I will remove it thanks.

**Comment by Morikko** [comment]
I am trying to keep the information updated as fast as possible. If you find again some missing information, don't hesitate to tell me.

**Comment by lucas-mancini** [comment]
Great, thanks!! Looks great.
