### ISSUE TITLE
Group backcup dialog popup constantly

### ISSUE THREAD

**Issue by xR2** [Morikko/sync-tab-groups#66]
I've even disable the backup for 5 mins, and disable the auto backup **at all**. Keep getting the annoying dialog to save the file.
In my understanding, the file should be saved automatically without any action from the user. Is something going wrong with my Firefox or what?

**Comment by fyta2000** [comment]
Also having this problem. Not sure how to make it stop.

**Comment by Morikko** [comment]
Can you check:
 Firefox Preferences > Files > Downloads 
Is "always ask where to save a file" checked ?

**Comment by xR2** [comment]
Yes I do, I consider that a security measure. 
However I don't get the dialog option to "remember my choice" in this case. I don't know if it would be safe to add the javascript file extension on to Firefox list, but that might be the only option for now.

**Comment by Morikko** [comment]
Just to clarify, you see 1 or 2 ?
1.
![image](https://user-images.githubusercontent.com/7831572/35567085-07142d54-05c4-11e8-8eb2-b75ce12b64bb.png)
2.
![image](https://user-images.githubusercontent.com/7831572/35567168-618593a4-05c4-11e8-9c79-b55c30c9cbf8.png)

Are you on FF 58 ?

---- 
Actually, I didn't set a parameter as before FF58, it was set by default to false. But from FF58, if not set the parameter takes the default value you have set (in this case the box is checked).

In any case, for next release I will force to false.

**Comment by Morikko** [comment]
Actually, I was still on FF57, I am currently updating 🙃

**Comment by Morikko** [comment]
With FF 58, I got Image 2. And if I force the option to false, it doesn't appear. It will be in next release (by the end of week) :)

**Comment by infopac** [comment]
I confirm that I have "always ask where to save file" in Firefox set; I am also using Sync Tab Groups and when it updated to version v0.50, it started asking me where to save the synctabgroups-backup-5mins.json file every 5 minutes. Disabling automatic backup in the addon fixed this.

So I think it is safe to say that the Firefox setting of "always ask where to save file" is conflicting with your addon. Perhaps you can set the backup folder to %appdata%\SyncTabGroups instead?

**Comment by Morikko** [comment]
Solved in 0.5.1
