### ISSUE TITLE
Can't drag and drop to rearange tabs when there is more than one row of tabs

### ISSUE THREAD

**Issue by fyta2000** [Morikko/sync-tab-groups#67]
There is a strange issue that is occurring when there is more than one row of tabs. Trying to rearrange the position of a tab by drag and drop, causes the tab to move to the first row, and cannot be moved from the first few tab slots.

There seems to be some conflict between a tabs position (x/y position), it's list position (1-dimensional list of all tabs), the number of tab rows, and the size of the tabs (which can be different for each row).

This might be more obvious if using a custom browser.tabs.tabMinWidth. I have mine set to 110.
(FYI: changing tab width: https://support.mozilla.org/en-US/questions/1186634)

**Comment by Morikko** [comment]
Are you talking about the bar above in the window ? Or Something in the Menu (Appear when you click on the extension icon) or in the Groups Manager tab ?

> when there is more than one row of tabs

Can you share a screenshot ?

**Comment by fyta2000** [comment]
The bar above the window where the tabs are.
Here is a screenshot. Three overlayed images, showing before moving a tab (more than one row of tabs), during moving of a tab (display of tab gets buggy), and finally where the tab ended up after the attempted drag.
![tabgoupstabmovingbug](https://user-images.githubusercontent.com/35937972/35583334-73fd63cc-05a6-11e8-9533-166b11fb8375.png)

As I mentioned in the original post, it might help to change the minimum tab width. This will help with getting multiple rows of tabs.

It is possible this is a Firefox bug, but since this is the only tab extension I have installed, I thought it could be caused by this extension.

I have Firefox 58.0.1, 64-bit on Windows.

**Comment by fyta2000** [comment]
OK, I apologize!
This has nothing to do with this extension.
Firefox by default only does left/right scrolling for tabs (not multiple rows). There is some css you can add to your profile to make the tabs span multiple rows instead of left/right scrolling.

Here for reference:
https://stackoverflow.com/questions/47361535/how-can-i-have-multiple-rows-with-tabs-on-firefox-57-tab-mix-plux-add-on-no-lo

**Comment by Morikko** [comment]
I was about to confirm you that Sync Tab Groups is not modifying or
controlling the tab bar.

And so, it was another cause. I am glad you found it already.
