### ISSUE TITLE
Errors in focused tab positioning when pinned tabs are included in groups

### ISSUE THREAD

**Issue by Kharmak** [Morikko/sync-tab-groups#68]
When the option 'Settings/Pinned Tabs' is switched to 'Included' and I open an existing group, position of the last focused tab is incorrect. Win7, Firefox 58.0.

If the focused tab is pinned, it appears at the very left instead of its position when the group was closed.

If the focused tab is not pinned and there are pinned tabs in the group, the focused tab appears right after the pinned tabs.

If there are no pinned tabs in the group, the focused tab appears as second one from the left.

Relative posiions of all the non-focused tabs are correct. The error affects only the focused one.

As there are no positioning errors when 'Settings/Pinned Tabs' is switched to 'Excluded', and there were no such errors in 0.4.1 both in Firefox 57 and 58, I hope it can be fixed. Anyway, it is a great add-on, thank you.

**Comment by Morikko** [comment]
> If the focused tab is not pinned and there are pinned tabs in the group, the focused tab appears right after the pinned tabs.

Confirmed

> If the focused tab is pinned, it appears at the very left instead of its position when the group was closed.

Confirmed

> If there are no pinned tabs in the group, the focused tab appears as second one from the left.

Not confirmed

However, I haven't investigated enough. I will study if the problem is at the opening time or depending of the group that was closed before.

**Comment by Kharmak** [comment]
Indeed, it depends on the group that was closed. Let's say I'm switching from group A to group B. The problem in B occurs only when A contains a pinned tab. So when I had pinned tabs in all my groups, the problem was permanent.

As to the 'not confirmed' problem with non-pinned tabs, the sequence number of the focused tab in group B seems to be important. Apparently, 1st and 2nd tab in B are not affected. But tabs 3, 4 etc. jump to 2nd place if A had pinned tabs. Well, maybe the 2nd tab is affected also, but it lands in the same place it has to be.

**Comment by duttyend** [comment]
Dear [Morikko](https://github.com/Morikko),
First of all, thank you so much for making this **great** extension !
I am also experiencing the same bug as Kharmak described very well. Hopefully, it isn't much hassle to fix.
Have a great week end!

**Comment by Morikko** [comment]
> First of all, thank you so much for making this great extension !

Thank you for your support :)

As regards to the 3 problems mentioned, I have written tests that passed after a correction. If something is still going badly in the next release, please refer to this issue again.

@Kharmak thanks a lot for your precise explanations.
