### ISSUE TITLE
json import from tabgroups failed

### ISSUE THREAD

**Issue by moscher** [Morikko/sync-tab-groups#69]
Hi,
i exported my groups in the extension form my old FF 56 with tabgroups.
When i did an import at sync tab groups 0.5 at my new FF 58 i get an error: 

ImportGroups: Content file is not in a supported format.

Can somebody help me please?

**Comment by Morikko** [comment]
I have two test files: 
 - One with tabs and pinned tabs
 - One with tabs and pinned tabs and the Session

Both are well imported. For further investigation:
 - Is it with Session or Without ? Does it fail in both cases ?
 - If you have no critical data, you can send me the file so I can try and fix it. (synctabgroups@gmail.com)
 - Else can you create an export file without critical data that fails ?

**Comment by moscher** [comment]
Thx for your answer! i have had a problem with the export. 
Now with the right json file i have a succsessfull import! 

But i get the next problem: 
https://github.com/Morikko/sync-tab-groups/issues/48#issuecomment-361709110

**Comment by leggewie** [comment]
@moscher: what kind of problem was it with the export? I'm currently in the same situation.  My import fails.
