### ISSUE TITLE
FeatureRequest: Sort the Groups

### ISSUE THREAD

**Issue by Morikko** [Morikko/sync-tab-groups#7]
Sort the groups per drag and drop.

I will first focus on some core functionalities and then add some UI possibilities.

@cyberpunkbln

**Comment by cyberpunkbln** [comment]
Hello,
thx and no problem, i know you code an panaroma feature what will be completly new with quantum and no old code can you use. Quantum was a shock for me that uses the TabGroups-AddOns long time and became after the update all tabs from all groups in one windows;). I think the new Panaroma takes the time that it needs for tab-junkies like me;).
greetz

**Comment by Morikko** [comment]
Finally it is :)
