### ISSUE TITLE
In FF Beta 59, clicking in the Search field or on the pencil (rename) icon closes the popup.

### ISSUE THREAD

**Issue by ElhemEnohpi** [Morikko/sync-tab-groups#77]
In FF Beta 59, clicking in the Search field or on the pencil (rename) icon closes the popup.

1. Create a clean profile in:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:59.0) Gecko/20100101 Firefox/59.0
2. Install Sync Tab Groups
3. Click on toolbar button, popup opens
4. Click on Search field or on the pencil (rename) icon.
Expected: able to enter text.
Actual: popup closes.

**Comment by Morikko** [comment]
I don't know if it is solved as well for you but I have no problem.

**Comment by ElhemEnohpi** [comment]
Fyi, I should have specified I was using the Developer Edition of FF 59.0b14 beta. It doesn't happen in the regular 59.0b14 beta, using the same profile. Strange...

Just updated to Dev Ed. 60.0b1, and it seems to be fixed.
