### ISSUE TITLE
Dropdown-group list disappears (cannot switch to other group)

### ISSUE THREAD

**Issue by maddhin** [Morikko/sync-tab-groups#82]
Hi,

when I click on the Sync-tab icon, the dropdown window with the groups only shows briefly (~1sec) and then disappears. So I cannot change groups anymore... 

Anybody any idea how to fix this? I tried restarting the browser and switching extension on/off. Both did not have any effect. 

Is there a shortcut to switch groups or something I can use in the meanwhile. 

Cheers!

**Comment by Morikko** [comment]
Can you check errors in  the console (ctrl + maj + j) ?

Are you on Chrome ?

Do you have access to the groups manager  ?

**Comment by maddhin** [comment]
I'm on Win10 with FF58

Do you have a Win10 shortcut for me?:)

If I remember correctly (I'm on different machine now), the groups manager was working (but I have not figured out how I can open a group out of the group manager).

Another point I forgot to mention: there is a small "leftover" of the dropdown-list window showing right next to the icon - same position as where the window "starts" with the little arrow. About the size of the icon. So, it seems the window "is still there" somehow but not open.

**Comment by Morikko** [comment]
I say it in French sorry :laughing: so it is (Ctrl + Shift + J).

If you have only this, the interface is broken.
![image](https://user-images.githubusercontent.com/7831572/36721854-5f0b04a8-1bac-11e8-989b-ac3a081d7a28.png)

Do you have the backups or manual exported groups ?

**Comment by maddhin** [comment]
OK, then my interface is broken... 

I assume I do have the backups if STG did the backups;)

**Comment by maddhin** [comment]
So this is the console errors:

          getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented.  jquery-1.9.1.min.js:3:31293
getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented.  jquery-1.9.1.min.js:3:31293
unreachable code after return statement  index.php:1:282
TypeError: url is undefined[Weitere Informationen] SessionStore.jsm:3522:9
	prepareConnectionToHost resource:///modules/sessionstore/SessionStore.jsm:3522:9
	speculativeConnectOnTabHover resource:///modules/sessionstore/SessionStore.jsm:3542:22
	speculativeConnectOnTabHover resource:///modules/sessionstore/SessionStore.jsm:345:5
	_mouseenter chrome://browser/content/tabbrowser.xml:8028:11
	onxblmouseover chrome://browser/content/tabbrowser.xml:8179:9
TypeError: this.props.tabs.map is not a function  tablist.js:13:7
Tastenereignis ist in manchen Tastaturlayouts nicht verfügbar: Taste="r" Modifikatoren="accel,alt" ID=“key_toggleReaderMode”  browser.xul
Tastenereignis ist in manchen Tastaturlayouts nicht verfügbar: Taste="i" Modifikatoren="accel,alt,shift" ID=“key_browserToolbox”  browser.xul
moz-extension://d0dffaa8-4c2c-4645-a7f1-af08497f8f15/background.html: chrome tabs query did not return a result while changing window focus


How can I fix STG? It's kind a terrible to be stuck in one group...

**Comment by k0286** [comment]
similar situation.

```
TabManager.getTabsInWindowId failed on window 3 with TypeError: new_url is null  tabmanager.js:60
GroupManager.detachWindow failed; groups[i].tabs.map is not a function  groupmanager.js:411
TabManager.getTabsInWindowId failed on window 3 with TypeError: new_url is null  tabmanager.js:60
GroupManager.detachWindow failed; groups[i].tabs.map is not a function  groupmanager.js:411
TabManager.getTabsInWindowId failed on window 3 with TypeError: new_url is null  tabmanager.js:60
GroupManager.detachWindow failed; groups[i].tabs.map is not a function  groupmanager.js:411
TabManager.getTabsInWindowId failed on window 3 with TypeError: new_url is null  tabmanager.js:60
GroupManager.detachWindow failed; groups[i].tabs.map is not a function  groupmanager.js:411
TabManager.getTabsInWindowId failed on window 3 with TypeError: new_url is null  tabmanager.js:60
GroupManager.detachWindow failed; groups[i].tabs.map is not a function  groupmanager.js:411
```

**Comment by maddhin** [comment]
is there any way to fix this problem (at least temporary)?

**Comment by Morikko** [comment]
> TypeError: this.props.tabs.map is not a function tablist.js:13:7

@maddhin 
One of your group has its tabs wrongly defined.
Don't you have a back up ? You can import the files from the Preferences and it will overwrite the current groups.

In future release, I will: 
- Add better error handlers in the UI
- Improve the core functions to try to fix on the go those errors (today, the extension only try to reload the groups from the local save in the browser. Usually, it works great but in your case it failed...)

> TabManager.getTabsInWindowId failed on window 3 with TypeError: new_url is null  tabmanager.js:60
GroupManager.detachWindow failed; groups[i].tabs.map is not a function  groupmanager.js:411

@k0286 
I understand the first error and will correct it. The second one is kind of strange but might be just a consequence of the first one.

**Comment by Morikko** [comment]
[This issue](https://github.com/Morikko/sync-tab-groups/issues/82#issuecomment-369139713) seems to be related to [the one](https://github.com/Morikko/sync-tab-groups/issues/48#issuecomment-362243057) opened by @moscher

**Comment by Morikko** [comment]
Normally, the error is solved! :tada: 

Next release is planned for this weekend. Let me know if it will be solved.

> is there any way to fix this problem (at least temporary)?

@maddhin  , what I discovered:
- Errors happened while looking to the tabs opened in the windows
- If you have a discarded tab opened by the extension, actually it is this url: moz-extension://68ddee50-febc-45b5-bd3d-f7c6264e02a5/tabpages/lazytab/lazytab.html?url=www.website.com
- Normally the tab updates automatically to www.website.com on activation
- The error appeared if the URL field is not defined

Thus, I recommend you to activate all your tabs and to close the tabs that don't update and without URL value.

**Comment by maddhin** [comment]
@Morikko: Thanks for your help!

I actually see that I do not have 1 day or 1 week backups although STG is already running for significantly longer than 1 week :) So, I do not have a "before-problem-backup" :(

Will the next release fix the issue without using a backup?

**Comment by maddhin** [comment]
@Morikko: just FYI: I used Alt + Shift + right to go through all the groups and erased 2-3 tabs (out of ~200!) that did not update. STG is working again. Cheers!
