### ISSUE TITLE
Panel too tall 

### ISSUE THREAD

**Issue by designakt** [Morikko/sync-tab-groups#85]
I would expect the panel to fit the content.
Like this I regularly forget that there are options at the bottom. And when I want to use those action, they are harder to reach.

![synctabgroups_panel-too-long](https://user-images.githubusercontent.com/8145891/36846540-5f1aa9e8-1d5b-11e8-9233-3d07a5d63be8.gif)

**Comment by Morikko** [comment]
That was the previous behavior. I changed to the actual one (I prefer) for avoiding the window to resize continuously.

I might add it, if other people are interested.
