### ISSUE TITLE
Authentication required

### ISSUE THREAD

**Issue by zabojpetr** [Morikko/sync-tab-groups#87]
Hi,
when I want to show list of groups, authentication required is pop up and the list is closed. This is happend every time, so I cannot switch groups. This page with popup is probably in any other group, so I cannot close this page.

Is there any preload or something like this, what causes this problem?

**Comment by Morikko** [comment]
> This page with popup is probably in any other group, so I cannot close this page.

Only opened group are loaded and tabs inside can trigger an authentication Popup.

> Is there any preload or something like this, what causes this problem?

The extension has no authentication pop-up. You might check your tabs or other extensions to find the real guilty.

**Comment by Morikko** [comment]
I apologized for the previous message. I forgot that the icon was fetched to the website and so could ask for the authentication. Other people told me about this problem. 

Can you respond to those few questions in Basic HTTP authentication prevents using the menu #76  ?
It is another thread about the same problem.

**Comment by zabojpetr** [comment]
A few days after I post this issue I was able to close groups (maybe bad connection). Now when I try repeat the problem, everything works properly.
---
So a few questions:

    What is your system ?
        Windows 10 EDU x64
    What is your FF version ?
        59.0.1 x64
    Is the previous link opening the popup ?
        No longer
    Even if you have updated to FF59 ?
    If no, can you share a link that always opens the popup
---
Good job, have a nice day.
