### ISSUE TITLE
FeatureRequest: Exporting / Importing Sessions

### ISSUE THREAD

**Issue by TRSyntax** [Morikko/sync-tab-groups#9]
Title says it all, but to clarify; i would like an option to set a default export directory, and a button to export all groups to session data from the firefox user interface. importing sessions from other add-on's would be a super plus but not at all necessary.

**Comment by Morikko** [comment]
> a button to export all groups to session data

What do you mean with session data ? Do you have an example ? What do you want to do with ?

>  importing sessions from other add-on's

Do you mean importing groups from other Sync Tab Groups Addon ?

**Comment by christianlupus** [comment]
I would like to see a similar feature to save effectively the tabs/tab groups in a file for backup or physical transportation to another firefox instance.
