### ISSUE TITLE
([subjectively] annoying) Save Animation is displayed for backups in Chrome

### ISSUE THREAD

**Issue by Lcstyle** [Morikko/sync-tab-groups#90]
All the save period timers are selected by default for the extension, this is fine as it safeguards against tab group loss.  Unfortunately, there's an odd symptom in Chrome, everytime the backup runs, a "Save File" animation is displayed at the bottom left of the browser.  The animation is a little disconcerting because it implies that there's some browser action happening that is being triggered by an external event, and it happens too frequently.  This animation of a file being saved is being subjectively interpreted by me as some kind of malicious browser script or some other such similar unintended problem such that I consider that potentially the extension should be enhanced so that the save file animation isn't displayed and the backup happens in the background.

I hope that makes sense, but it kind of freaks you out because it happens so often, and the fact that it's saving could be misinterpreted by those of us in the tin foil hat community as potentially some malicious process saving a screenshot of your activity, or some such similar UI/UX unpleasant experience.

Ironically, the worst part about this issue is the realization that if this truly was a malicious process running in your browser, it would probably never ever ever give the user any kind of interaction that it is there.  However, therein lies the crux of malware in that many times it's detectable by undesirable side effects and weird little quirky behaviors that it's authors cannot control or prevent as a result of it's illicit "injection" into your software, which is why the save animation was as disconcerting as it was (it triggered some pattern heuristics in my brain that said, something is wrong).

**Comment by Morikko** [comment]
This [comment](https://github.com/Morikko/sync-tab-groups/issues/88#issuecomment-371861466) explains the solution I will add.

Actually, I can't hide this effect (Probably browsers keep this to still prevent user)

**Comment by Morikko** [comment]
In v0.6.3, you can switch to local back up for avoiding this.
