### ISSUE TITLE
losing tabs while switching groups

### ISSUE THREAD

**Issue by maddhin** [Morikko/sync-tab-groups#91]
Hi,

I'm on Win10 with FF58. I just switched from one group to another and then back to the first group and 3 or 4 tabs are just gone!!! Only 2 tabs were left in the group. Odd. 

Here is the info from console if helpful:

`Content Security Policy: 'x-frame-options' wird wegen 'frame-ancestors'-Direktive ignoriert.  (unbekannt)
Content Security Policy: Die Direktive 'child-src' sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'worker-src' zum Kontrollieren von Workern bzw. die Direktive 'frame-src' zum Kontrollieren von Frames.  (unbekannt)
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://assets-cdn.github.com"). Source: ;!function(){var t=0,e=function(t,e){ret....  88:1
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://assets-cdn.github.com"). Source: (function (ERROR) {

    const V8_STACK_....  88:1
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://assets-cdn.github.com"). Source: call to eval() or related function blocked by CSP.  (unbekannt)
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://assets-cdn.github.com"). Source: window.klTabId_kis = 'firefox.tab.2d885e....  89:1
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://assets-cdn.github.com"). Source: document.currentScript.setAttribute("res....  89:1
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://assets-cdn.github.com"). Source: window.klTabId_kis = 'firefox.tab.45a9d5....  88:1
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://assets-cdn.github.com"). Source: document.currentScript.setAttribute("res....  88:1
moz-extension://5f2bb1a3-86bd-469d-8429-55fc7d56ebd1/background.html: chrome tabs query did not return a result while changing window focus
`

This is VERY unfortunate behavior as I have groups with say 20 or 30 tabs and I do not immediately recognize if 2-3 are missing... This could corrupt everything "quietly". 

Any solution?

**Comment by maddhin** [comment]
PS: after reimporting a backup, I do have all groups twice and had to manually remove the dublicate groups 

I think having solid backups are really crucial at this point;)

**Comment by Morikko** [comment]
> This is VERY unfortunate behavior as I have groups with say 20 or 30 tabs and I do not immediately recognize if 2-3 are missing... This could corrupt everything "quietly".

Again, no error is from the extension. I will test this weekend. However, without clue, if it is a deep bug, it might be hard to point.

Moreover, I never faced this problem...

> PS: after reimporting a backup, I do have all groups twice and had to manually remove the dublicate groups

Groups/Tabs selection are planned ;)

**Comment by maddhin** [comment]
I kind a resorted to trying not to change groups too often now as preventive measure :) However, I saw this behaviour in earlier versions as well but thought it was because the extension was still young/buggy. Back then I went back to the old tab groups extension. But now, on a productive system, loosing tabs/groups/backups is hard. 
Fingers crossed you find something!! THANKS!

**Comment by Morikko** [comment]
I have tested the extension over and over and things are good in v0.6.3.
If it happens to someone, you can continue on this thread.

**Comment by maddhin** [comment]
I'm not sure if "switching" groups is the cause but today I found that about 20 tabs got lost in my "every day browsing" group. Thanks to the new backup system, I was able to recover the tabs but it still seems an issue in 0.6.5. 
It's hard to me to compare if I also lost tabs in other groups as I have many groups with a lot of tabs (and the backup import function doesn't show how many tabs are in the groups).
Anything I can do to help fixing this?

**Comment by Morikko** [comment]
I am glad you could restore them with the back up. 

Actually, I would need:
 - the log for checking errors
 - a method to always do the problem so I could analyze the broken parts

I am focusing mostly on #64. After, I will look to add: 
 - a logging system easily exportable (for having the error logs)
 - a documentation to explain how to provide me useful information (only if done at the moment of the problem)

**Comment by maddhin** [comment]
I can provide the log if you can tell me how to get it;) 
Otherwise, I am not sure how to reproduce the issue - and frankly, I'm not very eager to reproduce the issue. I have too many groups (19) with with 5 to 50 tabs each (about 15-20 on average). If always only a few tabs get lost, it is hard to realize. I only realize it once I rotate back to that project but that can be 2-3 weeks later... So for the moment, I try not to jump too often between groups to minimize risk haha

Having an easy to export log would be super! Then it should be much easier/faster to find issues. 

At the moment, it seems very complicated to track down this bug unless somebody else also has this bug.

**Comment by maddhin** [comment]
I definetely can re-confim the problem on a different computer - I just found that I lost 13 out of 33 tabs in my most commonly used group. 
Thanks to the backup function, I now know around when it happened. I know that I switched back and forth a few times to a different group but I am certain I did not restart the computer/Firefox or anything dodgy happened.

**Comment by Morikko** [comment]
Can you check the [bug wiki page](https://github.com/Morikko/sync-tab-groups/wiki/How-to-help-me-solve-bugs). 
Any feedback about the explanations are welcomed.

I am using it at my company and at home and I never has the problem yet. My groups are usually smaller than 20 tabs so a loss would be quickly visible.

**Comment by Lcstyle** [comment]
I've experienced this behavior myself, but not recently. I will wait until I can provide specific repro instructions as well.  Now Mind you, I am running all kinds of other extensions in FF, though none of these extensions are related to tab manipulation specifically, nevertheless, so they could potentially be interfering.  For a good repro we'll need to test with a clean browser instance (fresh install).

**Comment by Morikko** [comment]
I am adding a logging to the extension you will only have to send it to me. With this, I would be able to track the behavior and errors more easily on those kind of problems.

**Comment by OlivierJG** [comment]
Sounds like https://bugzilla.mozilla.org/show_bug.cgi?id=1435077
