### ISSUE TITLE
Firefox: Open Sync Tab Group Menu does not focus on search bar

### ISSUE THREAD

**Issue by galan** [Morikko/sync-tab-groups#95]
When I open the Menu using the shortcut, the search bar is not focus, which is enforcing me to use the mouse to do so. Tested and worked in Chromium.
I'm using Firefox 59.0 64bit Linux.

**Comment by hdd60311** [comment]
This bug is fixed in firefox 60.
https://bugzilla.mozilla.org/show_bug.cgi?id=1324255

**Comment by galan** [comment]
9th may, yet another 8 weeks until a tab-group alternative for firefox is usable :(
Will stay will FF56 or switch to chrome. Thanks for the information! @hdd60311

**Comment by Morikko** [comment]
Thanks @hdd60311. I knew the bug but I didn't know they fixed it for FF60.

Note: pressing 2 times tab in FF will focus the popup, and thus finally
auto focusing the search bar. After, you can use any hotkeys to move
between the groups and tabs.
