### ISSUE TITLE
Sync tab group showing blank screen when using multiple Firefox windows

### ISSUE THREAD

**Issue by pichouk** [Morikko/sync-tab-groups#98]
Hi,

I use this extension everyday and, since I have a multi-screen setup, I usually have 2 Firefox windows opened (one for "static" stuff to keep an eye on, another one for browsing).
Before yesterday (and the `0.6.3` version) I was able to use Sync tab group on both windows, with the same groups synchronized : it was perfect.

Today when I open **one** Firefox window, everything is fine. But as soon as I opened a second Firefox window, the extension "crash" and dropdown menu + group manager page are showing a blank screen with the following error in my dev console.
```
TypeError​columnNumber: 13​fileName: "moz-extension://d890501e-3c65-42d7-9c0c-e7854a97d052/share/components/groups/grouplist.js"​lineNumber: 100​message: "this.props.groups[index] is undefined"​stack: "render@moz-extension://d890501e-3c65-42d7-9c0c-e7854a97d052/share/components/groups/grouplist.js:100:13\nh@moz-extension://d890501e-3c65-42d7-9c0c-e7854a97d052/lib/js/react-dom.production.min.js:130:362\nbeginWork@moz-extension://d890501e-3c65-42d7-9c0c-e7854a97d052/lib/js/react-dom.production.min.js:134:70\nd@moz-extension://d890501e-3c65-42d7-9c0c-e7854a97d052/lib/js/react-dom.production.min.js:158:393\nf@moz-extension://d890501e-3c65-42d7-9c0c-e7854a97d052/lib/js/react-dom.production.min.js:159:214\ng@moz-extension://d890501e-3c65-42d7-9c0c-e7854a97d052/lib/js/react-dom.production.min.js:159:462\nt@moz-extension://d890501e-3c65-42d7-9c0c-e7854a97d052/lib/js/react-dom.production.min.js:167:3\nx@moz-extension://d890501e-3c65-42d7-9c0c-e7854a97d052/lib/js/react-dom.production.min.js:166:247\nr@moz-extension://d890501e-3c65-42d7-9c0c-e7854a97d052/lib/js/react-dom.production.min.js:164:368\nv@moz-extension://d890501e-3c65-42d7-9c0c-e7854a97d052/lib/js/react-dom.production.min.js:163:278\nenqueueSetState@moz-extension://d890501e-3c65-42d7-9c0c-e7854a97d052/lib/js/react-dom.production.min.js:124:386\np.prototype.setState@moz-extension://d890501e-3c65-42d7-9c0c-e7854a97d052/lib/js/react.production.min.js:18:82\np/</a</p.prototype.onStateChange@moz-extension://d890501e-3c65-42d7-9c0c-e7854a97d052/lib/js/react-redux.min.js:1:4133\na@moz-extension://d890501e-3c65-42d7-9c0c-e7854a97d052/lib/js/redux.min.js:1:1247\npopupMessenger@moz-extension://d890501e-3c65-42d7-9c0c-e7854a97d052/share/components/groups/wrapper/group-actions.js:129:7\n"​__proto__: {…}​​constructor: function TypeError()​​message: ""​​name: "TypeError"​​stack: ""​​__proto__: {…}​​​constructor: function Error()​​​message: ""​​​name: "Error"​​​stack: Getter & Setter​​​toSource: function toSource()​​​toString: function toString()​​​__proto__: {…}​​​​__defineGetter__: function __defineGetter__()​​​​__defineSetter__: function __defineSetter__()​​​​__lookupGetter__: function __lookupGetter__()​​​​__lookupSetter__: function __lookupSetter__()​​​​constructor: function Object()​​​​hasOwnProperty: function hasOwnProperty()​​​​isPrototypeOf: function isPrototypeOf()​​​​propertyIsEnumerable: function propertyIsEnumerable()​​​​toLocaleString: function toLocaleString()​​​​toSource: function toSource()​​​​toString: function toString()​​​​valueOf: function valueOf() react-dom.production.min.js:162:310
```

I'm sorry for the simple and ugly copy-paste of the error. I don't even know if it helps, I'm not really a web developer ^^ Let me know if I can provide more/better information.

**Comment by pichouk** [comment]
FYI I revert to `0.6.2` and it works fine. So this is related to a change in the last release I guess :wink:

**Comment by pichouk** [comment]
I got something like this 
```
Array [ Object, Object, Object, Object, Object, Object, Object ] 
undefined
```
It returns an array objects with those values
```
[
  {
    "index": 0,
    "position": 1
  },
  {
    "index": 1,
    "position": 5
  },
  {
    "index": 2,
    "position": 0
  },
  {
    "index": 3,
    "position": 4
  },
  {
    "index": 4,
    "position": 2
  },
  {
    "index": 5,
    "position": 3
  },
  {
    "index": -1,
    "position": -1
  }
]
```

**Comment by Morikko** [comment]
This is the problem:
```
{ 
    "index": -1,
    "position": -1
}
```
Those values are normally well set after a change occurred in your groups (Open a new tab in a group, close a tab...).
1. Can you confirm me that you have seen no other error than the one you paste ?
2. Have you tried to open/close tabs in a group to see if things get fixed ?

By the way, I found other bugs in a function but your problem is the index equal to -1.

**Comment by allenyllee** [comment]
I have similar problem, and has the same result as @pichouk 
Also, I got a lot of error message as below

```
GroupManager.setTabsInGroupId failed; too much recursion groupmanager.js:433:5
	GroupManager.setTabsInGroupId moz-extension://c7153308-964d-4907-bd24-3a0f5455ae99/background/core/groupmanager.js:433:5
	TabManager.updateTabsInGroup moz-extension://c7153308-964d-4907-bd24-3a0f5455ae99/background/core/tabmanager.js:131:5
```

**Comment by Morikko** [comment]
@allenyllee you caught something interesting, any other errors maybe ?
Also, do you remember how the error appeared, what did you do ?

I am not able to reproduce it on my test session...

**Comment by allenyllee** [comment]
@Morikko Just click `Group Invisible`

![](https://screenshotscdn.firefoxusercontent.com/images/1e20be1d-8a61-4d87-8db8-2311ef8c7f05.png)

And things go down:

![](https://screenshotscdn.firefoxusercontent.com/images/b527a12b-567d-46cf-bd7a-d89c315b6983.png)

**Comment by Morikko** [comment]
Still only with this error ? 
`GroupManager.setTabsInGroupId failed; too much recursion groupmanager.js:433:5`

On my session the button is working well.

**Comment by allenyllee** [comment]
BTW, 0.6.2 doesn't have above error message

**Comment by Morikko** [comment]
On which FF version and which OS ?

**Comment by pichouk** [comment]
I have the issue on Firefox `58.0.1` on GNU/Linux (tested on Debian Stretch and Ubuntu `16.04`). It doesn't change anything if I try to open/close tab on my group and I was not able to find other error message.

**Comment by Morikko** [comment]
Fixed in v0.6.4
If it doesn't work directly on restart, uncheck/check the preference `Remove empty groups` in `Preferences > Settings`.

**Comment by allenyllee** [comment]
It works on Windows 10, Firefox 59.0.2
BTW, the tabs number had disappeared....

**Comment by pichouk** [comment]
Hi !
Yes i upgraded again to `0.6.4` and it works fine now ! :smiley: 
Thanks for the fix (and your reactivity :+1: ) !

**Comment by Morikko** [comment]
> BTW, the tabs number had disappeared.... 

Good catch, It will be fixed in the next release.
