### ISSUE TITLE
Lost my groups; Group Manager is blank

### ISSUE THREAD

**Issue by tkalee** [Morikko/sync-tab-groups#99]
Hi I posted a review [here](https://addons.mozilla.org/en-US/firefox/addon/sync-tab-groups/reviews/1090517/)

Thanks Marko for your reply! The post you linked to doesn't really describe my problem. This is what I see:
![sync tab troubleshooting](https://user-images.githubusercontent.com/37857433/38007355-04bcba66-3284-11e8-88b2-5c4ec52b2a5c.png)

When I right-click and choose Groups Manager, it opens to a [blank page](moz-extension://2f2a12eb-7a47-4dfc-949f-b8b3466cb158/tabpages/manage-groups/manage-groups.html).

I've tried importing groups from when Sync Tab Groups worked better, but nothing happens.

This morning, just before the problem started, my Firefox updated to 59.0.2 (64-bit). 

Help! I love your extension and would love to keep using it.

**Comment by pichouk** [comment]
Hi :)

It duplicates https://github.com/Morikko/sync-tab-groups/issues/98 which is now fixed. I invite you top upgrade again your extension :wink:

**Comment by tkalee** [comment]
Wonderful -- that worked perfectly. Thank you pichouk!
